### ISSUE TITLE
No way to view "additional options" or "donations" purchased so far.

### ISSUE THREAD

**Issue by doug86i** [alfio-event/alf.io#1012]
**Is your feature request related to a problem? Please describe.**
Lets say you're selling a product or a service as an "additional option", there is currently no way to find out how many you have sold so that you can have them made/be prepared.

The same goes for donations, there is no way to find out how much one should send to charity.

**Describe the solution you'd like**
A csv/excel download would be fine. or just a table with numbers!

**Comment by cbellone** [comment]
fixed. will be released with the upcoming M3-2105

**Comment by cbellone** [comment]
fixed and released as part of https://github.com/alfio-event/alf.io/releases/tag/2.0-M3-2107
