### ISSUE TITLE
The selected categories cannot be combined

### ISSUE THREAD

**Issue by wesleypearson** [alfio-event/alf.io#1018]
On this event (https://tickets.rallysportmag.com/event/2021arvsp) we are getting an error on the front where tickets are selected _The selected categories cannot be combined_

We are unsure what this means

<img width="1440" alt="2021-06-30 at 14 58 44 (Google Chrome-Reserve a Ticket for 2021 Alpine Rally VIP Spectator Tour!)" src="https://user-images.githubusercontent.com/46010020/123904410-c4db1e80-d9b3-11eb-9bff-d18c601c9465.png">

On the back end it looks to be creating a reservation but will not let you proceed. 
<img width="1434" alt="2021-06-30 at 15 01 46 (Google Chrome-Alf io Admin)" src="https://user-images.githubusercontent.com/46010020/123904635-2ac7a600-d9b4-11eb-953e-306b77d6f254.png">

**Comment by cbellone** [comment]
Hi,
there's a problem with the payment configuration. This error appears when there is now way for the user to pay for a given reservation.

You should have an error message in the log like this one:
`[ERROR] missing payment methods`

`[ERROR] Cannot proceed with reservation.`

they should give you some hints on what's wrong with the configuration
