### ISSUE TITLE
UPDATE: Stripe Payment Gateway

### ISSUE THREAD

**Issue by wesleypearson** [alfio-event/alf.io#1021]
https://checkout.stripe.dev/?mode=payment
https://github.com/stripe-samples/checkout-one-time-payments

Could we look at updating the stripe intergration to the next Stripe Checkout?

**Comment by wesleypearson** [comment]
@syjer

**Comment by cbellone** [comment]
Hi,

the current checkout integration is deprecated. You should use the embedded 3DS integration, as explained here: https://alf.io/docs/configuration/payment/stripe-sca/

**Comment by wesleypearson** [comment]
Amazing thank you
