### ISSUE TITLE
SMTP: Java protocol issues ...

### ISSUE THREAD

**Issue by mave-git** [alfio-event/alf.io#1029]
Hi, this is my first contact to and with alfi.io, trying and looking at it.

Installation is on cloud server (Hetzner), vserver Ubuntu 20.04 (4GB RAM, 40GB disk), running 2.0-M3-2107 (2021-07-04), Obenjdk-11. Seems to be fine, but:

no (smtp) mail is going out. I tried an own mail server (mail-in-a-box), posteo.de, hetzner-mail-server. Port 465, 587, smtp, smtps, even in smtp properties "mail.smtp.starttls.enable=true"; did made changes/playing in java.security activating TLSv1x ... nothing worked:

```
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
        at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170) ~[?:?]
        at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98) ~[?:?]
        at sun.security.ssl.TransportContext.kickstart(TransportContext.java:221) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411) ~[?:?]
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:527) ~[mail-1.5.0-b01.jar!/:1.5.0-b01]
        at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:464) ~[mail-1.5.0-b01.jar!/:1.5.0-b01]
        at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1902) ~[mail-1.5.0-b01.jar!/:1.5.0-b01]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666) ~[mail-1.5.0-b01.jar!/:1.5.0-b01]
        at javax.mail.Service.connect(Service.java:295) ~[mail-1.5.0-b01.jar!/:1.5.0-b01]
        at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
```
Sometimes: "could not connect to server XY on Port 587 or 465 ...

Any issues known?

Regards!

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox, Browser
 - Version: newest

**Additional context**
Server: Ubuntu Server 20.04, installed PostgreSQL (working), Obenjdk-11

**Comment by ken-bem** [comment]
Maybe this could help you: https://stackoverflow.com/questions/67899129/postfix-and-openjdk-11-no-appropriate-protocol-protocol-is-disabled-or-cipher

**Comment by cbellone** [comment]
Hi, 

can you please attach the whole stack trace that you have in the logs?

> what is the right syntax using inside the Alfi.io-Configuration GUI?
```properties
mail.smtp.ssl.protocols=TLSv1.2
```

back to the certificate, it appears that the host you're trying to connect to doesn't have a valid certificate:

```console
$ openssl s_client -connect my.boxmail.de:465
CONNECTED(00000003)
depth=2 C = PL, O = Unizeto Technologies S.A., OU = Certum Certification Authority, CN = Certum Trusted Network CA
verify return:1
depth=1 C = PL, O = Unizeto Technologies S.A., OU = Certum Certification Authority, CN = Certum Domain Validation CA SHA2
verify return:1
depth=0 CN = *.kasserver.com
verify return:1
---
Certificate chain
 0 s:CN = *.kasserver.com
   i:C = PL, O = Unizeto Technologies S.A., OU = Certum Certification Authority, CN = Certum Domain Validation CA SHA2
 1 s:C = PL, O = Unizeto Technologies S.A., OU = Certum Certification Authority, CN = Certum Domain Validation CA SHA2
   i:C = PL, O = Unizeto Technologies S.A., OU = Certum Certification Authority, CN = Certum Trusted Network CA
```

IMO this should return a valid certificate for my.boxmail.de. Instead it is returning a wildcard certificate for another domain.

for reference, here's the output for smtp-relay.gmail.com:

```console
$ openssl s_client -connect smtp-relay.gmail.com:465
CONNECTED(00000003)
depth=2 C = US, O = Google Trust Services LLC, CN = GTS Root R1
verify return:1
depth=1 C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
verify return:1
depth=0 CN = smtp-relay.gmail.com
verify return:1
---
Certificate chain
 0 s:CN = smtp-relay.gmail.com
   i:C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
 1 s:C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
   i:C = US, O = Google Trust Services LLC, CN = GTS Root R1
 2 s:C = US, O = Google Trust Services LLC, CN = GTS Root R1
   i:C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
```

**Comment by mave-git** [comment]
Ah! Should I start with a new database? I tried JDK 14 but on existing and new created events, event-urls are broken (error 404), Uuups ;-)

**Comment by mave-git** [comment]
... changing to JDK 13 brougt mismatch on created event-urls:
M3  for example: https://alfio.mvtool.de/event/gfgr-stammtisch
M4 => https://alfio.mvtool.de/alfio.mvtool.de/event/gfgr-stammtisch
Trying M4 booking an event: no mails outgoing. I'll reset the vserver, starting with new installation to avoid configuration issues while testing.

**Comment by mave-git** [comment]
... took news vservers, switching JDK's, firewalls, protocols. No success... so stopped working on alf.io meanwhile. Maybe on final state of 2.0 trying again.

**Comment by icougil** [comment]
Hi! 
We are facing here the same issue with Java 17 trying to use gmail when sending emails.
Do we need to include the extra SMTP config in the web/UI or not?
`mail.smtp.ssl.protocols=TLSv1.2`
Best

**Comment by vb-03** [comment]
![image](https://user-images.githubusercontent.com/47537857/192861436-ba54cc26-d179-4742-8d5d-ff3a213ec075.png)
Got Gmail working with this config and an "App Password" for the password field (requires 2FA)

**Comment by icougil** [comment]
Got it working with your configuration as well.
Thank you @vb-03 !

**Comment by tobsowo** [comment]
Thank you @vb-03 for helping to save time resolving this.

For anyone that might need to do this in future, here is the text version you can copy and paste:

`mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.smtp.ssl.enable=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.starttls.required=true`

**Comment by ChildApple** [comment]
Many Thanks @vb-03 your configuration worked on the latest production release of alfio on ubuntu 22.04 andusing a gmail account

**Comment by gverbist** [comment]
I cannot get this to work for the love of ......  using smtp2go.

In the logs I get :

[WARN ] 2024-07-24 12:09:55.112 [qtp2116511124-70] PageNotFound - No mapping for POST /session-expired
[WARN ] 2024-07-24 12:10:16.063 [scheduling-1] NotificationManager - Message with id 2 will be discarded
[WARN ] 2024-07-24 12:10:21.060 [scheduling-1] NotificationManager - Message with id 1 will be discarded
