### ISSUE TITLE
Error on "Confirmed" items on the Additional services page

### ISSUE THREAD

**Issue by RuiDom** [alfio-event/alf.io#1108]
**Describe the bug**
We've just run an event where attendees could pre-order fish and chips. We used the "Confirmed" figures on the Additional services page to order the food, which shows a total of 187 items (see screenshot). When we ran the end of event reports, we discovered that we had only received paymets for 80 items (see anonymised purchased items report). We have therefore made a loss on this of over £300, around 5.5% of total event income.

**To Reproduce**
1. Go to 'Additional services' page
2. Use the figures that are shown as "Confirmed" and check against the following
3. Export Purchased items

**Expected behavior**
"Confirmed" figures should equal the "Purchased items"

**Screenshots**
![image](https://user-images.githubusercontent.com/39782605/189803633-efd47552-9e00-4620-ac2f-0048cd00b1e0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Attachment**
Anonymised Purchase items report
[TF22-SUPPLEMENT(1).xlsx](https://github.com/alfio-event/alf.io/files/9553358/TF22-SUPPLEMENT.1.xlsx)

**Comment by syjer** [comment]
hi @RuiDom , thank you for reporting this issue, I'm able to reproduce the error locally, I'll make a fix ASAP.

**Comment by phedders** [comment]
Thanks for fixing this so quickly.
