### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by benharvie** [alfio-event/alf.io#1148]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@rezaduty) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by cbellone** [comment]
Hi @benharvie thanks for reaching out, and for pointing out the missing security policy!

Will close this issue for now, please send us an email so that we can discuss the details. Thank you!
