### ISSUE TITLE
Stripe payment method idempotency_error when card is declined on first try

### ISSUE THREAD

**Issue by Chircop97** [alfio-event/alf.io#1254]
**Describe the bug**
Whenever I try to make a payment via Stripe and the card gets declined and I try again, the application then provides an idempotencyException. This is due to the first request being done using the same reservation key.

**To Reproduce**
1. Try and make a payment making sure it fails for some reason
2. Once its failed go ahead and try again
3. See Error stating the idempotencyException

**Expected behavior**
This behaviour shouldn't happen and while the reservation should still remain intact, there should be a way to either get a new reservation ID or use another key.

**Screenshots**
This first image shows the first request with the card being declined.
![image](https://github.com/alfio-event/alf.io/assets/37708144/806374e6-871f-4295-98b9-f39718872bf7)

The second image shows the second request with the idempotency error due to using the same reservation ID as the idempotency key.
![image](https://github.com/alfio-event/alf.io/assets/37708144/9f1ecf79-720f-4a55-858b-d912ffb66c66)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 114.0

**Comment by cbellone** [comment]
Hi @Chircop97,

thanks for using alf.io!

By looking at the payload, it seems that you are using Stripe without having configured [Strong Customer Authentication](https://alf.io/docs/configuration/payment/stripe-sca/).

can you please confirm if that's the case?

**Comment by Chircop97** [comment]
That is in fact the case, I will go ahead and implement this and let you know with my result. Thanks

**Comment by Chircop97** [comment]
Hi, so I've tried setting it up with Strong Customer Authentication and created the webhook etc, however when I try to do a payment it seems that alf.io hangs waiting for some type of response. When having a look at the logs on stripe webhook. I noticed that the request was received to stripe but had a 500 error stating that the payment provider has not been found.

![image](https://github.com/alfio-event/alf.io/assets/37708144/fc6d3880-b52f-435b-babe-40a4c695e30a)

**Comment by cbellone** [comment]
please double check that the configuration is consistent across levels (system, organization, event).
please double check that the "base url" configuration does not have a trailing slash at the end

If everything looks OK to you, please share screenshots of the actual configuration on all levels (see above) for the following sections:

- Payment -> general
- Payment -> stripe

Please mask / hide actual configuration values, I am only interested in seeing which options are set at which level, in order to reproduce the issue.
Thanks

**Comment by Chircop97** [comment]
1. System Level
![image](https://github.com/alfio-event/alf.io/assets/37708144/926445cc-7997-4574-8da2-cf4a8b8b8fbb)
2. Organization Level
![image](https://github.com/alfio-event/alf.io/assets/37708144/62c18dec-70ad-4592-82d6-701968eef946)
3. Event Level
![image](https://github.com/alfio-event/alf.io/assets/37708144/81728328-9ca1-4565-ab47-598e0f982962)

I also checked the base URL that it doesn't have a trailing slash and its also set on all levels. The issue still persists. Something to point out is that I have an NGINX reverse proxy infront of the alfio. However traffic is not being blocked to /api endpoints, already verified it.

**Comment by cbellone** [comment]
Apologies for getting back to you so late.

I would suggest you a couple of things:

1. unless you have different organizations on the same instance running their ticket sales, configure stripe at system level and delete all the configurations from organization and event level

2. You probably don't need stripe connect, unless you are acting as a platform provider for multiple organizations. See https://stripe.com/en-ch/connect for more information

3. Check on the alf.io logs for any errors.

**Comment by Chircop97** [comment]
So, I got rid of all the configurations and left the one under system only, now im having this weird problem not sure if you ever envountered it before. It seems that the pay stays greyed out and there is no field were to input card details.
![image](https://github.com/alfio-event/alf.io/assets/37708144/ac3b9d4b-5818-4bc7-90ad-8ee390f44909)

**Comment by cbellone** [comment]
The Stripe widget is not loading, the configuration is probably incorrect.
You should have an error on the browser console, can you please check? It should clarify **why** the widget is not being loaded

**Comment by Chircop97** [comment]
Ok so you were right the PK was missing fro mthe organization hence why it wasn't loading the integration. I set the the values as needed and the integration loaded. After pushing a test following the setting up, I resulted in an error on stripe, "payload not recognized"
![image](https://github.com/alfio-event/alf.io/assets/37708144/28600caf-9766-43c8-b5b6-eca94ec4755d)

**Comment by Chircop97** [comment]
By any chance, could it be that the platform is sending live data while in fact it should be sending test data? Since the keys im using from stripe are in test mode. If so from were can i set this within alfio?

**Comment by Chircop97** [comment]
Update: I have re-created the webhook using the latest API version and it works successfully without any problems. Thanks for your genuine help
