### ISSUE TITLE
Custom email email token

### ISSUE THREAD

**Issue by tobsowo** [alfio-event/alf.io#1269]
Sending an email using the {{eventName}} token showed correctly during the preview but when the email was sent, it used the slug in the event.

**Comment by cbellone** [comment]
Note for first-time contributors: this issue is referring to the "compose custom message" functionality.
To access it:
- create a new (free) event [how-to](https://alf.io/docs/event-setup/create-in-person-event/)
- simulate some (free) registrations
- click on Actions -> compose message
![image](https://github.com/alfio-event/alf.io/assets/3385346/49924fae-0201-4dbe-8572-7bd3ee48c979)

**Comment by ved-asole** [comment]
Thanks @cbellone, I will go through the process and would try to take care of the above bug

**Comment by ved-asole** [comment]
> Sending an email using the {{eventName}} token showed correctly during the preview but when the email was sent, it used the slug in the event.

@tobsowo - If possible can you share a sample of what inputs you gave and what kind of output email was sent along with the slug?

**Comment by cbellone** [comment]
> Thanks @cbellone, I will go through the process and would try to take care of the above bug

Please note that this fix must be done on the `2.0-M4-maintenance` branch

**Comment by ved-asole** [comment]
sure

**Comment by tobsowo** [comment]
@ved-asole I'm not on PC, I'll do that once I get the chance.

**Comment by ved-asole** [comment]
sure, Thanks @tobsowo 😊

**Comment by tobsowo** [comment]
If you look at the token on the right {{eventName}} is interpreted as **sep23** but in the preview it was the right token. When the email is sent, it is sep23 that is used instead of the event name.
![image](https://github.com/alfio-event/alf.io/assets/5642737/1382c167-61c1-4093-a693-a91c056e6d3e)


Preview
![image](https://github.com/alfio-event/alf.io/assets/5642737/ab31430c-44f8-46cf-abac-373885286409)

**Comment by ved-asole** [comment]
Oh. ok @tobsowo. So you mean that the {{eventName}} value should be the `Integrating Mautic and Wordpress [Meetup]` as per your configuration but it's coming as `sep23` ? Please correct me if I'm wrong.

**Comment by tobsowo** [comment]
You're correct.

**Comment by ved-asole** [comment]
Thanks for confirming. I will check and resolve it.

**Comment by ved-asole** [comment]
Hi @cbellone, thanks for approving the pull request. 

Hi @tobsowo, this issue is resolved as part of the `2.0-M4-maintenance` branch. It will deployed in `2.0-M4-maintenance ` version.

**Comment by tobsowo** [comment]
Thank you for the update
