### ISSUE TITLE
Google API Key should be optional

### ISSUE THREAD

**Issue by cbellone** [alfio-event/alf.io#127]
see #126

**Comment by BunsenMcDubbs** [comment]
Is anyone working on this right now? If not, I wouldn't mind taking a look in the next 1-3 weeks

**Comment by cbellone** [comment]
Hi @BunsenMcDubbs, 
thank you, that would be highly appreciated.

Please note that on dev environment, there is no call made to the google maps server API (geolocation / timezone), as the [DefaultLocationManager] (https://github.com/exteso/alf.io/blob/1844efdd8202c8dc6a39308c209ff7871224e549/src/main/java/alfio/manager/location/DefaultLocationManager.java) is not enabled.

**Comment by BunsenMcDubbs** [comment]
I'm going to experiment and play with it tomorrow but I think this is very promising: http://www.intertech.com/Blog/spring-4-conditional-bean-configuration/

Using this instead of or with the Profile annotation to switch between DefaultLocationManager and MockLocationManager

**Comment by BunsenMcDubbs** [comment]
[6a909bd](https://github.com/BunsenMcDubbs/alf.io/commit/6a909bdff5bc50425872d91bd1b4eae0cb7fa74e) does not work. see [my comment](https://github.com/BunsenMcDubbs/alf.io/commit/6a909bdff5bc50425872d91bd1b4eae0cb7fa74e#commitcomment-18188330)

**Comment by BunsenMcDubbs** [comment]
@cbellone what do you think of my approach in [40daea0](https://github.com/BunsenMcDubbs/alf.io/commit/40daea0ba52d9adc169417b01ff66ee117e26940)?

If there is no API key then we use the MockLocationManager. I'm going to take a look at removing maps in the front end as well. Do you have any suggestions?

**Comment by cbellone** [comment]
Hi Andrew,

Apologies for the delay.

I don't think that we can use the MockLocationManager in a production
environment.
The problem is that the MockLocationManager always returns "Europe/Zurich"
as time zone for the event, and that would be simply wrong in most cases.

I think we could do the following:

1) If google maps server api key is missing, enable the "event time zone"
field (select? Input + autocompletion?) on the GUI

2) change the return type for all methods in the LocationManager interface
from T to Optional<T>, and return Optional.empty() in case of error or
missing key

3) modify the event validation/insert process accordingly (if geocode or
getTimezone return empty, then validate and use the "event time zone" input
value)

How does it sound?

Il 16-lug-2016 4:31 PM, "Andrew Dai" <notifications@github.com> ha scritto:

**Comment by BunsenMcDubbs** [comment]
@cbellone Unfortunately I won't be able to work on this for a while. My organization has found another solution. I am still interested in staying involved but I'll have to take a step back for the next month or so.

**Comment by cbellone** [comment]
Hi @BunsenMcDubbs ,
don't worry, and thank you very much for your help.
Hope to hear from you soon :)
Celestino

**Comment by syjer** [comment]
has been implemented some time ago :)
