### ISSUE TITLE
Ability to have booking fee a percentage of ticket price

### ISSUE THREAD

**Issue by doug86i** [alfio-event/alf.io#1283]
**Is your feature request related to a problem? Please describe.**
Currently we can add a booking fee as a fixed price Additional Option and make it Mandatory - One for each ticket purchased. It's common for us to have different priced tickets and it would be useful to be able to have the booking fee a percentage of the ticket price.

**Describe the solution you'd like**
What would be perfect would be to have a radio button on the additional options dialogue to select between "fixed price" and "percentage of ticket price"

**Describe alternatives you've considered**
Another option would be to have a separate admin area for booking fees and have options for fixed price or percentage, If it's tricky to implement within the current additional options framework.

**Additional context**
Let's say we offer a high priced VIP week long ticket for say £200 - We want to cover the credit card processing and platform fee on this large price so set the booking fee to something high like £10. 

Now imagine we offer a very cheap ticket for children on just one day at £10. now that £10 booking fee is very high.

This is a feature available on all the commercial ticketing platforms I've used so feel it's a worthwhile addition.

Thanks for reading! x

**Comment by cbellone** [comment]
hi @doug86i , that makes definitely sense. Thank you for suggesting this feature!

**Comment by doug86i** [comment]
@cbellone I would be interested in sponsoring development of this and potentially some other features. Who is best to speak to about this?

**Comment by cbellone** [comment]
Hi @doug86i 

Great! 

It would be ideal if you could send an email to `hello _at_ alf.io` with more details about your use case and the features you'd like to sponsor; then we can set up a first online call to discuss about next steps.

How does it sound?

**Comment by doug86i** [comment]
Perfect, will email now x
