### ISSUE TITLE
When Ticket categories are growing dynamically, the additional option is not functioning as aspected.

### ISSUE THREAD

**Issue by justusweigmann** [alfio-event/alf.io#1286]
**Describe the bug**
We would like to offer customers the possibility to receive their reserved tickets printed. However, this is currently not possible. Our ticket categories 'grow dynamically'. If the customer selects our 'Shipping per order' (OPTIONAL_MAX_AMOUNT_PER_RESERVATION) option, we encounter the error in the web frontend: 'Ticket category is not available,' and the network message is 'error.STEP_1_TICKET_CATEGORY_MUST_BE_SALEABLE.' However, the tickets are currently available for booking, and the option is also available for booking.

**To Reproduce**
1. The user selects from the ticket categories.
2. The user selects the additional option "Shipping per order."
3. The user receives the error message "Ticket category is not available", "error.STEP_1_TICKET_CATEGORY_MUST_BE_SALEABLE."

**Screenshots**
<img width="1857" alt="Bildschirmfoto 2023-10-07 um 13 55 33" src="https://github.com/alfio-event/alf.io/assets/95694564/e93e54e3-027b-498b-9734-27b9cdb91860">

**Desktop (please complete the following information):**
 - OS: MacOS, iPadOS, iOS
 - Browser Brave, Safari

**Additional context**
Failed to load resource: the server responded with a status of 422 ()
{
    "value": null,
    "validationErrors": [
        {
            "fieldName": "reservationForm",
            "code": "error.STEP_1_TICKET_CATEGORY_MUST_BE_SALEABLE",
            "arguments": null
        }
    ],
    "errorCount": 1,
    "success": false,
    "warnings": []
}

**Comment by cbellone** [comment]
Can you please create a similar event on our [demo instance](https://demo.alf.io/admin) (see #1022 for more info on how to login), and try to reproduce the problem there?
Then please let me know the event slug as soon as you have it, so that I can have a look

thanks

**Comment by justusweigmann** [comment]
Hey,

As requested, I have replicated the issue on the demo instance (https://demo.alf.io/event/test-github). If you need any further information, simply let me know.

**Comment by justusweigmann** [comment]
Thanks for the fix. I will update my instance soon. Any idea when a new Docker image is published with the changes?

**Comment by cbellone** [comment]
we are finalizing the new release, so I would say in the next few weeks.

In the meantime, it would be of great help if you could test the "dev build" using the following image:
https://github.com/alfio-event/alf.io/pkgs/container/alf.io%2Fdev-2.0-m4-maintenance

and confirm that everything's working as expected.
Thank you!
