### ISSUE TITLE
Stripe as payment provider not showing

### ISSUE THREAD

**Issue by justusweigmann** [alfio-event/alf.io#1311]
**Describe the bug**
Hello there!

I just tried to set up the Stripe integration. Unfortunately, Stripe is not displayed on the sales page for the customer.

![Screenshot 2023-12-22 at 21 31 07](https://github.com/alfio-event/alf.io/assets/95694564/b3303747-c79a-4a19-acf1-fbd7a9954422)

**To Reproduce**
1. Choose a card
2. Enter billing address
3. Assign tickets
4. Select payment method
5. Stripe Credit Card option not displayed

**Expected behavior**
Show the Stripe Credit Card option.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari and Firefox
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 17.2.1
 - Browser Safari
 - Version latest

**Additional context**
Stripe Setup in alf.io
<img width="1538" alt="Screenshot 2023-12-22 at 21 30 10" src="https://github.com/alfio-event/alf.io/assets/95694564/1f4aa8f8-f48c-418e-ac73-6e75bb43bdc3">

**Comment by cbellone** [comment]
please make sure to mark "Stripe: credit cards" as accepted payment method for your event

(Seats and payment info -> edit)

![image](https://github.com/alfio-event/alf.io/assets/3385346/a981ce23-4d0f-46f2-b15b-63032c298638)

**Comment by justusweigmann** [comment]
Yes, it's enabled. The only thing that I turned off is the platform charges for that particular customer.
