### ISSUE TITLE
Can't create Organizations

### ISSUE THREAD

**Issue by titi1125** [alfio-event/alf.io#1334]
After installation can not create organizations.

**To Reproduce**

1. Go to 'Organizations'

2. Click on 'Name and put in Org Name, Contact E-Mail and put in E-Mail, Description and put in Description'

3. Scroll down to 'Save and click on Save'

4. See error:
Internal Server Error: Cannot invoke %26%2334%3Bjava.lang.Integer.intValue()%26%2334%3B because the return value of %26%2334%3Balfio.model.modification.OrganizationModification.getId()%26%2334%3B is null

![image](https://github.com/alfio-event/alf.io/assets/86929103/6c3695bb-d541-4ba4-8b4f-ee51a62f3eba)

**Comment by syjer** [comment]
Hi @titi1125 thanks for reporting this issue, we are aware of it, we will fix it and do a release as soon as possible.

**Comment by titi1125** [comment]
Hello @syjer ,
thank you for the fast feedback. 
Do you also have the solution? Because i think is an important think, without organization you can't use this system.

**Comment by syjer** [comment]
Hi @titi1125 a fix has been done, a new release is in the pipeline
