### ISSUE TITLE
Hyperlink at location field

### ISSUE THREAD

**Issue by titi1125** [alfio-event/alf.io#1338]
is it possible to implement a hyperlink at the location field?

according to the printscreen:
![image](https://github.com/alfio-event/alf.io/assets/86929103/69547b51-f172-42ec-afd6-93267222ad73)

**Comment by syjer** [comment]
hi @titi1125 , currently not. And we don't think we will allow the user to enter any markdown value in this field, as it's also used in non html context.

But what we can do is, if you use a supported map provider, in the web app to auto generate a clickable link.

**Comment by titi1125** [comment]
ok, from my point of view you can close this issue
