### ISSUE TITLE
Mollie Test/Live payment failing

### ISSUE THREAD

**Issue by Tiddons** [alfio-event/alf.io#1382]
**Describe the bug**
After correctly setting up mollie (i think), we keep getting errors when trying to make a payment with mollie.
![image](https://github.com/user-attachments/assets/6a9770c2-ee4a-464a-9def-4cc5bcf779e9)

Going into the logs, there appears the following error:
`[qtp345060426-89] WARN  alfio.manager.payment.MollieWebhookPaymentManager - was not able to create a payment for reservation id 11cxxxx-xxxx-xxxx-xxxx-xxxxx392e`

This is our configuration:
![image](https://github.com/user-attachments/assets/408f3e1c-6aa0-43fa-a848-58d73457a71f)
![image](https://github.com/user-attachments/assets/46f8e81f-771c-456b-bd0c-001e6829bccf)

Our server runs on Ubuntu 20.04 and we use docker for the deployment

thanks in advance

**Comment by cbellone** [comment]
Hi!

please double check the value of the "Base URL" setting at System and Organization level.
It must be a valid URL, i.e. `https://my-domain.com`, otherwise Mollie will reject the payment request.

**Comment by Tiddons** [comment]
Putting https:// in front of the url fixed it. 
Perhaps there should be a way to notify the user about writing this before their url.

Thanks!

**Comment by cbellone** [comment]
Indeed, that's a known problem. 
It would be great if you could open a new issue for it, and we'll fix it while we migrate the admin frontend to the new architecture
