### ISSUE TITLE
Keycloak SSO OpenID Configuration Help 

### ISSUE THREAD

**Issue by mcm2007** [alfio-event/alf.io#1402]
**Describe the bug**
So im trying to setup OpenID so the public can "create" and login on their own accounts to save their infos as it was intended.
However i am unable to get it to work as no matter what i try i always recive a 500 error after all...
![image](https://github.com/user-attachments/assets/3715026d-bb81-40f4-857b-1983140461fc)

**To Reproduce**
1. Went to Keycloak to setup everything (version 25.0.1):
1.1- Created an new client (alfio) on an new realm according to the documents provided (thoes i could understand)... and the initial configuration was like this: 
![image](https://github.com/user-attachments/assets/88cb139c-7bd7-43a0-8fef-59107a499ecd)
![image](https://github.com/user-attachments/assets/6d4549e0-c638-45a8-8968-e0d77681f12c)
![image](https://github.com/user-attachments/assets/80284bd6-bc30-45c7-945d-24e48a35f418)
Then on the alfio scopes role mappers, i have inserted some dedicated ones as shown here
![image](https://github.com/user-attachments/assets/359767ab-62b6-416b-926f-d8d3df073af4)
![image](https://github.com/user-attachments/assets/7b00eddb-ddf4-463e-b22e-aeb3e2422d40)
![image](https://github.com/user-attachments/assets/dafcc58a-ca82-46ba-bc9e-805af9a2ed2e)
There is also 2 roles on the realm:
![image](https://github.com/user-attachments/assets/8999f5fe-2d3d-4823-9270-0eb42aa44eab)
And in groups an parent group with 2 child groups:
![image](https://github.com/user-attachments/assets/3877dede-39d1-4615-948c-15fbb2e7bdc0)

2. After all that went to the admin web UI headed into configurations and set up the OpenID section like this:
![image](https://github.com/user-attachments/assets/1fe89a7f-5f54-4d74-9a73-f6a730230ed0)
*Dont worry about the secret as it has been reset
3. After saving and going into an incognito tab (why not), the login actually appears but it always comes with an error... Most likely from missconfiguration that is what im trying to figure out...

**Expected behavior**
Users be able to login into the SSO Keycloak interface and have their profiles saved

**Desktop (please complete the following information):**
 - OS: Currently Running 2.0M4 on heroku
 - Browser chrome

**Additional context**
If anyone have an "step by step" would be ideal as i already messed the configuration of keycloak so bad that i am already lost...
The Keycloak provider is served behind an zoraxy proxy with SSL.

**Comment by cbellone** [comment]
public openid configuration requires a JSON configuration
see https://github.com/alfio-event/alf.io/discussions/1379#discussioncomment-10101209 for an example.

**Comment by mcm2007** [comment]
Hey again, so after viewing the thread and following (copying almost) the config i came across some challenges...
So here is the current config:
{
	"domain": "sso.the.provider",
	"clientId": "alfio",
	"clientSecret": "secrethere",
	"callbackURI": "the.alfio.domain/openid/callback",
	"authenticationUrl": "/realms/therealm/protocol/openid-connect/auth",
	"tokenEndpoint": "/realms/therealm/protocol/openid-connect/token",
	"rolesParameter": "roles",
	"alfioGroupsParameter": "org-roles",
	"logoutUrl": "/realms/therealm/protocol/openid-connect/logout",
	"logoutRedirectUrl": "https://the.alfio.domain/admin"
}

You might see that in the callbackURI i dont have the protocol on it, as if i put it down (https://the.alfio.domain/openid/callback) the result is an Incorrect redirectURI from keycloak. And after analysing the logs this is what i found: Sep 11 16:05:09 keycloak kc.sh[148]: 2024-09-11 16:05:09,820 WARN  [org.keycloak.events] (executor-thread-112) type="LOGIN_ERROR", realmId="xxxx", realmName="therealm", clientId="alfio", userId="null", ipAddress="chillbro", error="invalid_redirect_uri", **redirect_uri="https:/ticketlane.herokuapp.com/openid/callback"**
So as you see in the redicrect_uri it is missing an slash and because of it the keycloak dosent accept it...
If i remove the protocol on both alfio and keycloak client config i can sucessfully login. However probably because of the incorrect redirecturi after the login it goes to an 404 page with the following url: https://the.alfio.domain/the.alfio.domain/openid/callback?state=moreids&session_state=moreofthat&iss=https%3A%2F%2Fsso.the.provider%2Frealms%2Frealm&code=token.
If i manually remove the 2nd part of the.alfio.domain that is on duplicate it sucessfully logs in and runs "almost" smooth.

The 2nd issue is when trying to logout that it shows this error: Invalid parameter: redirect_uri with the following url: https://sso.the.provider/realms/therealm/protocol/openid-connect/logout?redirect_uri=https://the.alfio.instance/admin
On the logs that shows as Sep 11 21:12:56 keycloak kc.sh[148]: 2024-09-11 21:12:56,123 WARN  [org.keycloak.protocol.oidc.endpoints.LogoutEndpoint] (executor-thread-176) Parameter 'redirect_uri' no longer supported. Please use 'post_logout_redirect_uri' with 'id_token_hint' for this endpoint. Alternatively you can enable backwards compatibility option 'legacy-logout-redirect-uri' of oidc login protocol in the server configuration.
If i remove the "redirect_uri=https://the.alfio.instance/admin" i can sucessfully logout but without the redirect (ofc). As far as i moved this is what i got...
