### ISSUE TITLE
Add external reference to export of attendees' data

### ISSUE THREAD

**Issue by SilentResonance** [alfio-event/alf.io#1422]
**Is your feature request related to a problem? Please describe.**
I'm importing from an external questionaire software via CSV. The questionaire creates a reference column, which is used at import to alf.io. After the check-in is finished we need to have the given reference at the export to match the persons for out tournament software.

**Describe the solution you'd like**
While looking through the code I found the part, where the query is created in service.js and downloadAllTicketsCSV() in EventApiController.java. And in there, the exportLines() function creates the field list to be exported.
Furthermore, I found out, that a reference column is specifically added, with the attendee CSV import.

What I would like to have is a checkbox to tick, when a reference column exists and its contents exported to CSV

**Describe alternatives you've considered**
Implementing it myself, but I find it hard how to setup a development environment for alf.io which directly replaces the docker instance.
I want to keep it dockerized instead of native installation in order to keep my OS clean.
Any hints and help are appreciated.

**Additional context**
 - Docker container: alfio/alf.io:latest
 - Alf.io version: v.2.0-M5

**Comment by cbellone** [comment]
[hack-commit-push] note: to run a database locally with Docker:
`docker run -d --name alfio-main-postgres -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_DB=alfio --restart unless-stopped postgres
`

**Comment by cbellone** [comment]
[hack-commit-push]: Here's a simulated import file
[simulated-attendees.csv](https://github.com/user-attachments/files/17879327/simulated-attendees.csv)

it's currently missing the "external reference" value in the column, and it assumes that your event has the following "additional data to collect" defined:

- company
- country
