### ISSUE TITLE
Certificate of attendance and emailing to checked-in attendees only

### ISSUE THREAD

**Issue by BENETNATH** [alfio-event/alf.io#1440]
I need to provide to checked-in attendees a PDF certificate of presence with name, date and content of the workshop.
I need to email them, either this PDF certificate, or just a link to download or to generate it on the fly

**Describe the solution you'd like**
It would need to work on the check-in module, to add the capability to generate a certificate, with a predefined template, filled with event information, and also the ability to email only to checked-in attendees

**Describe alternatives you've considered**
Just having the possibility to email to checked-in attendees could be a first step, and creating a email template in this case might partially solve the problem, but the PDF is really a better outcome

**Comment by cbellone** [comment]
Hi,
this is a problem that you can solve by implementing a dedicated (micro)service which can be triggered by the [Ticket checked-in extension](https://alf.io/docs/reference/extensions/reference/ticket/#ticket-checked-in).

The easiest solution would be to implement a transactional email template with [Mailjet](https://www.mailjet.com/blog/product/designing-perfect-transactional-email-templating/) and then invoke their [API](https://dev.mailjet.com/email/guides/send-api-V3/#use-a-template) to send the email.
Other providers have similar solutions.

Hope this helps
