### ISSUE TITLE
Show contextualized error message when saving a new event doesn't work

### ISSUE THREAD

**Issue by alessandro-giardina** [alfio-event/alf.io#192]
I try to create a new event with the data shown in the screenshot below. When press the "Save" button, nothing happens. I don't get neither error messages nor other kind of feedback:

![testrc1](https://cloud.githubusercontent.com/assets/4352322/18209373/bd4aa304-7133-11e6-801c-614e2f93fcae.jpg)

**Comment by cbellone** [comment]
I think somehow we've fixed this :P
