### ISSUE TITLE
Define a discountPolicy for each category

### ISSUE THREAD

**Issue by yankedev** [alfio-event/alf.io#220]
It could be useful to apply a special discount for reservations with many tickets (in the same transaction).
For example apply 10% discount if you buy 5 or more tickets.
Another nice policy could be to do:
- get 6 tickets, pay 5
- get 11 tickets, pay 9
- get 15 tickets, pay 12

The discount policy should be applied before any VOUCHER discount and must be visualized in the confirmation page and in the final invoice

**Comment by cbellone** [comment]
will be implemented as defined in #869
