### ISSUE TITLE
servor error when a click on bouton "continue"  at the end  of step 1  select

### ISSUE THREAD

**Issue by antonyfrance** [alfio-event/alf.io#253]
Hi !

I am testing again  alf.io  1.8.1 in heroku with postgresql.

 one  issue  when (for a event  ) i click on  bouton  "continue" at the end of step 1  select.

i can not go to the step 2 .
i have  HTTP ERROR 500
 Server Error
Caused by:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.samskivert.mustache.MustacheException$Context: No method or field with name 'request' on line 7

i try  to understand the source of this issue. ...Sometime   i have the issue..Sometine  i have not...!!!!!

have you got a idea ???

best regards

**Comment by cbellone** [comment]
Hi @antonyfrance,

could you please update alf.io to the latest version (1.9.3)?
Anyway, I think that the error could be related to a missing configuration for the selected payment method. 

Cheers,
Celestino

**Comment by antonyfrance** [comment]
Hi Celestino,
I will explore both solutions. During the testing periode, i am using  stripe api key,  but with free of charge configuration in alf.io.

Iconfirme that i will translate resources\alfio\i18n in french
Cheers,

Antony

**Comment by cbellone** [comment]
Hi @antonyfrance,

did you have the opportunity to reproduce again this issue? 

Thank you very much
Celestino

**Comment by antonyfrance** [comment]
I have always the problem, but i haven't found any solution ! But i will continue !
Best regards

Antony
