### ISSUE TITLE
Currency missing

### ISSUE THREAD

**Issue by sibivs** [alfio-event/alf.io#259]
Dear Team,

I am Varghese, from Bahrain. I was trying the Alf.io system on Heroku. I am able to set it up, integrate with google geo location etc. But i cannot find the BHD currency under the "Seats and payment info".
Please let me know how to add the missing currency

**Comment by cbellone** [comment]
Hi Varghese,

thanks for your interest in alf.io!!

At the moment we support only currencies with two decimal places. As far as I know, BHD uses three decimal places, right?

I think that we could add support for your currency in the next release (1.11). Could you help us with the testing?

Celestino

**Comment by sibivs** [comment]
Dear Celestino,

Thanks for the response.
For sure its my pleasure to test it.


--
Varghese

**Comment by syjer** [comment]
will switch from our custom implementation to http://javamoney.github.io/ri.html . This will largely improve our current situation :D

**Comment by kazarrugh** [comment]
Hello,
I installed Alf.io on my server, but I can't find my local currency 'LYD'
Is there a way to add it in any of the tables in postgres? Thanks.

**Comment by syjer** [comment]
hi @kazarrugh , currently we don't support some currencies due to some assumptions in the code. We will fix this issue in the 2.0 release (by switching to https://www.joda.org/joda-money/ ).

Sorry for the inconvenience.

**Comment by kazarrugh** [comment]
Hello @syjer, thanks for your feedback.  Please let me know when it will be added so that I can test it. Thanks a lot!

**Comment by cbellone** [comment]
This should be fixed now on master.
@sibivs, @kazarrugh : It would be great if you could test it. If you need access to our test platform please let me know.

Thanks for your patience and your help! :)

**Comment by cbellone** [comment]
![image](https://user-images.githubusercontent.com/3385346/61993058-5de5ba00-b066-11e9-8525-3d622ef2f362.png)

I guess we can consider it implemented :-)
