### ISSUE TITLE
Add Mollie as a payment gateway

### ISSUE THREAD

**Issue by mg-1999** [alfio-event/alf.io#286]
In the Netherlands we use iDEAL for almost all of our online transactions and not everyone has a creditcard. In Belgium is it almost the same, but they use Bankcontact there.
It also adds the option to add the main online payment methods of France and Italy. And handle SEPA-transactions with automatic callbacks.

All of this is in mollie and would be a great addition to the creditcard payment processors.

@cbellone suggested that I already do some digging in the flow and found a nice api doc and flow graphic.
![image](https://cloud.githubusercontent.com/assets/6923382/25408074/072acae8-2a0d-11e7-8754-a77d39b4128a.png)
Source: https://www.mollie.com/nl/docs/overview

Also noticed that there is an api available right here: https://github.com/stil4m/mollie-api

Hope that this is a good start for a nice addition.

- Matthijs

**Comment by syjer** [comment]
Hi @mg-1999 , thanks for opening the issue, the flow seems similar to the paypal one, I guess it should not be too hard to integrate it. I hope that they have some kind of test accounts :)

**Comment by mg-1999** [comment]
You can open a test account and you don't have to verify anything

**Comment by syjer** [comment]
cool :+1: thank you. I'll have a look :)

**Comment by mg-1999** [comment]
Is there any help that I can provide?

**Comment by syjer** [comment]
@mg-1999 , I think I have all the necessary informations to implement it :). Thank you :)

**Comment by syjer** [comment]
The work is in progress.

TODO:
 - [ ] when the reservation has been created, set to a processing status and then wait for the webhook to be called
 - [ ] webhook for handling the state transition
 - [ ] admin: don't let the user select mollie if the event is not paid in €
 - [ ] client ui: handle the "processing" state of the reservation
 - [ ] handle refund

**Comment by cbellone** [comment]
As of https://github.com/alfio-event/alf.io/commit/648ef6b80041c09f14dd3fbc6b86e4581dadf625, this can be considered implemented
