### ISSUE TITLE
Unexpected change email owner notification on ticket update

### ISSUE THREAD

**Issue by mariofusco** [alfio-event/alf.io#287]
I received an email with a link to download my ticket for Voxxed Days Ticino. I clicked on the link in the email, update a few data (company, country and language) in the form and clicked on the "Update Ticket" green button. Everything seemed to be ok and I received another email with the invitation and a copy of the ticket attached. However I also received an unexpected third email saying:

"Notice: the owner email of the ticket for event Voxxed Days Ticino 2017 has changed from xxx.xxx@gmail.com to https://tickets.voxxeddays.com/event/vdt17/ticket/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/update?lang=en. Please check at {3} if it's correct and fix it in case of any errors."

Environment:
Firefox 53.0 (64-bit)
Ubuntu 16.04 LTS

**Comment by cbellone** [comment]
should be fixed now
