### ISSUE TITLE
Internal Error on admin profile

### ISSUE THREAD

**Issue by flexwie** [alfio-event/alf.io#370]
I have set up Alf.io according to [this manual](https://gist.github.com/flexwie/a8572e8e7ef06ae844925ec857fa3b5b).

When I access the profile settings page for the admin account I get [this error](https://gist.github.com/flexwie/61a1f3c917dbbc15c895a375cd93666c) in the console and can't change the password because the 'Save' Button is just a spinning wheel.

Any ideas what could cause this?

**Comment by cbellone** [comment]
This could be a bug. Could you please share the entire alfio.log? (you should have it under logs/)

Thanks

**Comment by flexwie** [comment]
I added the complete log to the gist

https://gist.github.com/flexwie/61a1f3c917dbbc15c895a375cd93666c
