### ISSUE TITLE
403 on staticmap

### ISSUE THREAD

**Issue by flexwie** [alfio-event/alf.io#372]
When I access an event page, the map is not displayed correctly. Instead it shows an 403 error in the console. I have used a new and valid api key.

**Comment by cbellone** [comment]
sometimes new keys could get up to 1h to be distributed across all google maps' nodes. Do you still have the problem?

if yes, could you please check if the following APIs are enabled?

- [Google Maps JavaScript API](https://console.developers.google.com/apis/api/maps-backend.googleapis.com/overview)
- [Google Static Maps API](https://console.developers.google.com/apis/api/static-maps-backend.googleapis.com/overview)

**Comment by flexwie** [comment]
The Static Maps API did the trick for me, thank you!
