### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by lukebrewerton** [alfio-event/alf.io#375]
When running ./gradlew clean I get the following errors preventing full compilation:-

FAILURE: Build failed with an exception.

* Where:
Build file '/root/projects/alfio/build.gradle' line: 225

* What went wrong:
Could not compile build file '/root/projects/alfio/build.gradle'.
> startup failed:
  build file '/root/projects/alfio/build.gradle': 225: unable to resolve class java.time.format.DateTimeFormatter
   @ line 225, column 1.
     import java.time.format.DateTimeFormatter
     ^
  
  build file '/root/projects/alfio/build.gradle': 224: unable to resolve class java.time.ZonedDateTime
   @ line 224, column 1.
     import java.time.ZonedDateTime
     ^
  
  build file '/root/projects/alfio/build.gradle': 223: unable to resolve class java.time.ZoneId
   @ line 223, column 1.
     import java.time.ZoneId
     ^

**Comment by cbellone** [comment]
Hi @lukebrewerton,

could you please share the output of the following commands:

```
$ java -version
$ javac -version 
```

many thanks
Celestino

**Comment by lukebrewerton** [comment]
Sorted it, I installed JDK8 but 7 was already installed and was being used. Using Alternatives to switch to JDK8 resolved the issue
