### ISSUE TITLE
As organization owner I cannot register for checkin on mobile

### ISSUE THREAD

**Issue by pleinad** [alfio-event/alf.io#378]
Using an organization owner account it is not possible to register the app to scan the ticket during event. To manage the checkin I have to register another account with "checkin operator" role.

**Comment by cbellone** [comment]
this is completely normal. Please check https://alf.io/tutorials/check-in/

**Comment by pleinad** [comment]
Ok thanks, this is not completely clear reading the documentation. But ok, if I want to scan tickets with mobile application, I have to create another account with the specific role. Now it is clear. :-)
Thank you,
Daniel.
