### ISSUE TITLE
How to enable Paypal payments?

### ISSUE THREAD

**Issue by cougil** [alfio-event/alf.io#381]
Hi!
We'd like to enable Paypal payments, but we don't know exactly how we can do it. We tried to fill the "Paypal REST API Client ID" + "Secret" plus our "Paypal demo username" and "password" in our "Organization" config section, but in the page of the event, the option to pay with Paypal it is not enabled. How we can enable it?
Also, we suppose the Client ID + Secret it should be our Sandbox one, isn't it? Just to try that the payments are working, etc and then move to live. Are we following the correct mechanism to try to setup Paypal in Alf.io?
Best,

**Comment by cbellone** [comment]
Hi @cougil ,

> We tried to fill the "Paypal REST API Client ID" + "Secret"

great! Now you should enable "Paypal" as payment method in your event page, under "Seats and Payment info":

![image](https://user-images.githubusercontent.com/3385346/35780533-0d8a9b92-09dd-11e8-9414-fada1d0aeea7.png)

click on edit and then enable PayPal and save:

![image](https://user-images.githubusercontent.com/3385346/35780545-41f435a0-09dd-11e8-9d7b-cab2a1591d68.png)

then you should see it in your event page.

> plus our "Paypal demo username" and "password"

this is not necessary, as paypal demo username and password are for "demo mode" (like demo.alf.io). We'll clarify that in the settings GUI

> Also, we suppose the Client ID + Secret it should be our Sandbox one, isn't it? Just to try that the payments are working, etc and then move to live

Yes, correct. While using PayPal sandbox env:

1) please make sure you deactivated "live mode" for PayPal

![image](https://user-images.githubusercontent.com/3385346/35780577-d0c648d6-09dd-11e8-8b62-da0a8b0e6f43.png)

2) please make sure to use the sandbox accounts (usually *your-username*-buyer@...) as defined in the sandbox section

If I were in your shoes, I would also do a test with live credentials, just to be sure the keys are entered correctly. After doing a live payment, you can refund it by cancelling the corresponding reservation in alf.io

**Comment by cbellone** [comment]
Hi @cougil, can we close this issue?

**Comment by cougil** [comment]
Yes @cbellone sorry for being late checking your reply. 
It make totally sense to close it! I forgot to enable the payment mechanism under the Event page and it was always deactivated. May be a warning, tip, or something similar could help to the "admin" of the system to understand where they should go to enable it in some event ;-)
