### ISSUE TITLE
Mark the login qrcode for mobile app

### ISSUE THREAD

**Issue by pleinad** [alfio-event/alf.io#382]
As check-in operator on iPhone
I want to distinguish my login qr-code with a special mark
in order to avoid confusing with the ticket qr-code

Note: For example it could have a red border and a specific text saying: "Warning: this is a login qr-code and it contains credential to login using mobile application. Store it in a secure place and use it only when you need to login with a new device".

Thank you for your attention.
Daniel.

**Comment by cbellone** [comment]
This should be solved in #486
