### ISSUE TITLE
Statics in `/resources` are not served from Tomcat 9

### ISSUE THREAD

**Issue by abelsromero** [alfio-event/alf.io#387]
Hi,

I am deploying the WAR from the releases section in a Tomcat on Ubuntu and I see that the static content is not served.
I can start the app, but when I log into the admin console I see that things under `/resources` return 404.
For instance, https://my-domain/resources/angular-templates/admin/partials/configuration/basic-settings.html.

Is that by design?

**Comment by abelsromero** [comment]
OK, the issue seems to be some url that point to the absolute path `/`.
Deploying as ROOT fixed the issue, but still I think it would be nice to be able to deploy with a web app context.

**Comment by cbellone** [comment]
Hi @abelsromero,

thank you very much for your feedback. 

Supporting this kind of use case is not a priority for us, since we don't have any production instance that would need it. But if you're interested and willing to help, we would be very happy to receive a PR for that.

Thanks!
Celestino
