### ISSUE TITLE
Paypal payments not working - INVALID_EXPERIENCE_PROFILE_ID

### ISSUE THREAD

**Issue by cougil** [alfio-event/alf.io#393]
Hi.

We've found a new issue with Paypal. We have just updated the real _client ID_ and _client secret_ (only in the system configuration, we didn't setup anything in any other place) and we found that now it is not possible to pay with Paypal (even we checked that everything was working perfectly in the "demo mode" with the Paypal demo user/pwd). 

This is what we are seeing in the log:

`
ERROR com.paypal.base.HttpConnection - Response code: 400	Error response: {"name":"INVALID_EXPERIENCE_PROFILE_ID","message":"The requested experience profile ID was not found","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"XXXXXX"
`

What we are doing wrong? What we can do?

Best,

**Comment by syjer** [comment]
hi @cougil , actually you found a bug :). For performance reason I've cached the profile id (see https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/manager/PaypalManager.java#L59 ).

But I've not taken in account the change of  secret key. As a simple workaround, you can restart the instance so the cache is empty.

**Comment by cougil** [comment]
Done, thank for your super fast reply!
It is working right now after the restart ;-)

**Comment by syjer** [comment]
@cougil I'll reopen the issue so I can track my commit with this issue :)

**Comment by syjer** [comment]
should be fixed now,  @cougil  thanks for finding the bug :+1:
