### ISSUE TITLE
Dynamic CSS templates and system look

### ISSUE THREAD

**Issue by archenroot** [alfio-event/alf.io#394]
Hi, I am opening here request to add feature where will be supported dynamic CSS and images used on the system.

These templates will can be activate by multiple parameter:
- unique identificator

We plan to integrate alf into partners site, but the system will be running at our data center. So when called from partner 1, it should look similar to partner site 1 graphics. For partner 2, it should load partner 2 graphics.

This is because of customer trust.

I plan to work and pull back this feature once done.

**Comment by archenroot** [comment]
Any hints about where to start, or what are core areas of interest while trying to implement this could help... thx guys.

**Comment by syjer** [comment]
hi @archenroot , it's something that we want to do for the release 2.0 where we will expose for both "user" and "admin" a well defined and stable REST api, so it's more easy to write custom front-end.

This will take some time, so if you are really in a hurry, you can use the "configuration" mechanism that we have (see https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/manager/system/ConfigurationManager.java#L124 ) where you can define for a given key a value (clob in the database) that can be override from global to organizer to event granularity.

Then a new @Controller could be defined that return the custom css.

**Comment by archenroot** [comment]
Nice, actually I am looking to deploy full system in about 2 months, also if any help needed, I can hire someone to help you guys little bit.

When do you plan release 2.0?

And of course thank you for this system!!! I am more backend, but got a task to create reservation system and at first I though we must go with php, etc. But as I ma java guy, I am happy to found this beautiful project.

Ladislav

**Comment by cbellone** [comment]
Hi @archenroot,

> Nice, actually I am looking to deploy full system in about 2 months, also if any help needed, I can hire someone to help you guys little bit.

That would be amazing! Thank you! If you do that we will add your company's logo on our website, under the "Feature Sponsors" section (WIP), after we release v2.
Another option would be to sponsor the work of one of us. @syjer for example could take some time off, as he's a freelance, and work full time on alf.io for the time needed.

Just fyi, here's our "external contributions" policy, which we apply in case of substantial modifications:

- all the modifications must be discussed and agreed upon with the core committers before each new development
- every modification during development must be discussed within the team
- all the code must be covered by unit **and** integration tests
- all the code must adhere to what discussed at the beginning, or to every modification agreed upon during the development
- two people will review the code (and request changes if needed) before approving a pull request

> When do you plan release 2.0?

As Alf.io is a side-project (yet) for us, we cannot afford strict deadlines. The original plan was to release v2 by Q4 2018. The more external help we get, the earlier we can release :-)

Celestino

**Comment by archenroot** [comment]
I started email communication on this.

**Comment by ebartz** [comment]
How did this thing end? I would also love to change the css for some events to make sure the event pages fit out CI guidelines.

**Comment by syjer** [comment]
hi @ebartz , it has been implemented in https://github.com/alfio-event/alf.io/pull/922 , so it should be in the next release.

It's a little bit raw (basically, you add another css on top of the existing one), but it works.

**Comment by ebartz** [comment]
Hi @syjer, thanks for the information. I just saw that you closed the issue and the related pr. Do you have any information on the timeline for the new release?

I wanted to try this out next week - so I kinda just wanted to know if it makes sense to go through the build process or if I should just wait until you release the next version :)

**Comment by syjer** [comment]
hi @ebartz , most likely we won't be able to do a release next week.

Anyway, building from master should be easy enough.
