### ISSUE TITLE
Ticket scanning from Android via QR or other code system

### ISSUE THREAD

**Issue by archenroot** [alfio-event/alf.io#396]
HI guys,

the more I look into alf the more I like it. I found some non public older project regarding ticket scanning. In general, do you support QR or something to put on ticket generated from reservation? I didn't tested so far.

Thank you.

**Comment by syjer** [comment]
Hi @archenroot , yes, the tickets have a qrcode for the check-in. For scanning we currently have 3 options:

 - an android app made in java/kotlin (https://github.com/alfio-event/Alf.ioBackoffice/tree/android-native-maintenance)
 - an ios app made in nativescript (https://github.com/alfio-event/Alf.ioBackoffice)
 - a "scanning station" built with a rasperry-pi and a handheld qrcode reader. That we have used at various conferences (the biggest one is the Devoxx Belgium)
