### ISSUE TITLE
OpenShift deployment documentation

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#403]
The current documentation about how to deploy Alf.io on OpenShift seems to be for OpenShift v2 (its old pre-Kubernetes based version), and was GUI screenshot instead of automatable CLI based. 

It would be cool to have documentation showing how Alf.io can be deployed to OpenShift v3 (like the public cloud on OpenShift.com, or locally on minishift for development). It would also be a cool OpenShift show case... ;-) 

I have made a start with exploring that this weekend, see https://github.com/alfio-event/alf.io/compare/master...vorburger:openshift... it's still very much WIP, incomplete (thus no PR, yet) - but I thought I would already share this here anyway... ;) Will update this when usable!

**Comment by syjer** [comment]
hi @vorburger, thank you for doing the update, we were discussing about it recently :)

By the way, if you want, you can also submit a PR for the website too :) (https://github.com/alfio-event/alf.io-website/tree/gh-pages/tutorials/openshift).

**Comment by vorburger** [comment]
I now [have this fully running](https://tickets.learn.study) (using 1.x-maintenance and no longer master, following the hint in #511), see https://github.com/alfio-event/alf.io/compare/1.x-maintenance...vorburger:openshift_1.x-maintenance ... just cleaned it all up now, and raised (a first) **PR #524**!  

Here's some gaps that I will leave open for some future additional contribution (from me or anyone else wanting to help with this):

- [ ] add suitable Readiness & Liveness Probes healthcheckes to both Alf.io ([Actuator](https://stackoverflow.com/questions/46014206/kubernetes-liveness-and-readiness-probe-implementation)) & PostgreSQL
- [ ] use a Template, pwd as arg
- [ ] use a secret for the password
- [ ] monitoring for both Alf.io JVM, Spring Boot tracing and PostgreSQL performance & health
- [ ] rename the postgresql-95-centos7 service
- [ ] make it trigger a (first) build automatically on apply

**Comment by vorburger** [comment]
#604 fixes #524
