### ISSUE TITLE
Invoice with VAT included VS additional option

### ISSUE THREAD

**Issue by cougil** [alfio-event/alf.io#405]
Hi again!
We've seen that when you have an additional option and the prices of the event are taxed, it seems that the additional option doesn't look quite right.
For example, in our case (for the [Java and JVM Barcelona conference](http://www.jbcnconf.com))  ;-)), the ticket is 250€ (VAT 21% included) but the fee is 6€ (VAT included) and as you can see the image does not reflect the fee has VAT also:
![image](https://user-images.githubusercontent.com/2370634/37351741-0b99c58a-26dc-11e8-94e3-9093f5fe3d87.png)
We think the invoice should reflect that the additional option must show the value without the VAT included (then the total and subtotal amount will appear correctly).
Best,

**Comment by cbellone** [comment]
Thank you @cougil , this is a bug. We'll fix it in the upcoming 1.14
