### ISSUE TITLE
Introduce GDPR Privacy Policy link

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#419]
It would be great if we could add a privacy policy link to the event registration page. 
This would allow the event organiser to inform the attendees about their GDPR related efforts. 

When the link is empty, you can just hide it.

![image](https://user-images.githubusercontent.com/179457/39539011-ddd3ad02-4e3e-11e8-8c6b-ff356ac3b680.png)

**Comment by cbellone** [comment]
should be implemented.
