### ISSUE TITLE
Slash in organization name makes requests fail

### ISSUE THREAD

**Issue by salmar** [alfio-event/alf.io#424]
Having a slash in the organization name (like in Spring I/O) makes all requests containing the organization name fail. The following exception is thrown:

`org.springframework.security.web.firewall.RequestRejectedException: The requestURI cannot contain encoded slash. Got /admin/api/extensions/setting/organization/Spring%20I%2FO/event/eventname`

The affected version is 1.14.1. Also, by looking at the paths and URLs, seems that `eventname` is not properly replaced (compared to previous versions which contained the name of the event in the URL).

**Comment by syjer** [comment]
Hi @salmar , you are right, my bad.

I'll push a fix asap.

**Comment by salmar** [comment]
Works great now, thx

**Comment by cbellone** [comment]
ready to be released as part of 1.14.2
