### ISSUE TITLE
Add support for Canadian Tax Code (GST)

### ISSUE THREAD

**Issue by ToddCostella** [alfio-event/alf.io#431]
As I'm likely the first Canadian user of your fine system, I noticed that the tax information is European centric. In Canada we don't have VAT we have a Goods and Services Tax (GST). We are also required to specify a "GST Number" which should be displayed on invoices and payment receipts.

**Comment by syjer** [comment]
Taking care of it:

properties key that need an additional level of indirection:

- show-event.incVat
- show-event.excVat
- reservation-page.vat-included
- reservation-page.vat
- email-confirmation.vatNr
- invoice.vat
- invoice.vat-invoice
- invoice.validate.vat
- invoice.vat-voided
- reservation-page.vat-validation-required
- reservation-page.vat-validation-error

**Comment by syjer** [comment]
Implementation wise: 
 - we will let the user define a custom text for the sale tax name for each locale to override the default ones at global/organization/event level

**Comment by syjer** [comment]
should be implemented now. You can override the "VAT" term with a custom one.
