### ISSUE TITLE
Enforce VAT country code with country selected by ticket holders

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#434]
**Is your feature request related to a problem? Please describe.**
The VAT country code returned by VIES is the official one to decide the VAT rules. 
It should also be used to validate the country ticket holders and eventually also the contact person.

If they don't match the VAT country code, then the registration can not be made.

**Describe the solution you'd like**
You want to have an official source (for example VIES EU check) to validate the country where the customer is located.  This is needed to apply the correct VAT rules.

**Comment by cbellone** [comment]
implemented
