### ISSUE TITLE
The possibility to turn-off "I don't know yet who will attend"

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#436]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/179457/40239771-4ddd48f4-5ab7-11e8-9939-adfce98fa9d1.png)

The event organiser should have the possibility to turn-off "late ticket assignments" on the registration page.  

**Describe the solution you'd like**

We want to avoid that fake usernames are used during the registration process.  We require the exact names upfront.

**Comment by syjer** [comment]
taking care of it.

**Comment by syjer** [comment]
Implementation wise:

 - a new configuration key DISABLE_LAZY_TICKET_OWNER_ASSIGNMENT will be added (for global, org, event override) with a new "Reservation" category

**Comment by cbellone** [comment]
implemented. A new option has been added for this:

![image](https://user-images.githubusercontent.com/3385346/40587767-f5b83700-61d3-11e8-891a-110752bbd49b.png)

if enabled, the checkbox "I don't know yet who will attend the event" will be turned off
