### ISSUE TITLE
Missing I18N entry 'reservation-page.expiration-month' for en_GB 

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#438]
**Describe the bug**

The I18N public.properties key/value entry 'reservation-page.expiration-month' is missing for en_GB

![image](https://user-images.githubusercontent.com/179457/40267283-ae250be0-5b5a-11e8-8c81-3d6f4b79cc82.png)

**To Reproduce**
1. Start ALF.io locally using gradle bootRun
2. Register a non-free ticket and click continue
3. Exception will be shown

**Comment by syjer** [comment]
@stephanj , you have some property that are not separated by a newline: 
- https://github.com/devoxx/alf.io/blob/master/src/main/resources/alfio/i18n/public.properties#L76
- https://github.com/devoxx/alf.io/blob/master/src/main/resources/alfio/i18n/public.properties#L331

**Comment by syjer** [comment]
Btw, the key `reservation-page.expiration-month` is already present https://github.com/alfio-event/alf.io/blob/master/src/main/resources/alfio/i18n/public.properties#L76 . 

I think that error was launched when the 2 property were on the same line (don't know why)

**Comment by stephanj** [comment]
Indeed, strange but ok now
