### ISSUE TITLE
Promo code should have optional "total usage" counter

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#441]
**Is your feature request related to a problem? Please describe.**

Alf.io supports promo codes but I believe not the possibility to mention how many times the promo code can be used.   For Devoxx Belgium, we provide one promo code per sponsor which can be used 12, 10, 8 or 6 times.   

The current ALF.io implementation will force us to create 200 promo codes, or manually delete a promo code when the total has reached?

![image](https://user-images.githubusercontent.com/179457/40269834-be3e6e12-5b83-11e8-9ced-b7b0f86641b9.png)

**Comment by cbellone** [comment]
Yes, currently you cannot limit promo codes usage within their validity range.

We can implement the promo code usage limitation in v2, after the introduction of #276 (we'll publish the new datamodel soon)

In the meantime, alf.io allows you to do that by creating one category for each sponsor or custom reservations. Here's how.

Let's suppose that _SomeCo_ is sponsoring Devoxx BE, and they can have 12 tickets at half price.

### 1. Create a dedicated category for each sponsor and share Access URL / Send unique discount codes

You can create a restricted category for each sponsor and then specify an access code, which will allow users to acquire directly one ticket for this category

![image](https://user-images.githubusercontent.com/3385346/40270136-372fb0ca-5b88-11e8-8b27-9290f50184e5.png)

once you have defined an access code, you can share the Access URL

https://_your-instance-address_/event/_your-event_/code/NEWCO_BASE_SPONSOR

if you don't want to share a single URL, you can share the access tokens or send an invitation email for each of them

![image](https://user-images.githubusercontent.com/3385346/40270284-50608f36-5b8a-11e8-8efc-325d98addc3c.png)

### 2. Create a custom reservation

another option is to create a custom reservation (Actions -> Create Reservation). 
- You can create new categories or specify existing ones
- Reservations created by admin are not subjected to "public" constraints (e.g. you can add 10 people on it even if the official limit is 5, etc.)

![image](https://user-images.githubusercontent.com/3385346/40270300-b6790744-5b8a-11e8-9108-d06456cc4a15.png)

**Comment by cbellone** [comment]
implemented
