### ISSUE TITLE
Have the ability to change "VAT" to some other nomenclature (eg GST)

### ISSUE THREAD

**Issue by aidanmountford** [alfio-event/alf.io#444]
In AU the term that is used for VAT is GST.   

Whilst many accept that these are the same thing the is a requirement to use the correct term "GST". 

Variabalising this based on system/organsation would be useful. 

I note that some of the outputs can be changed by changing the templates but it would be good to make this easy for new users.

**Comment by cbellone** [comment]
Hi @aidanmountford 

thank you for using alf.io :-) 

we have solved a very similar issue a couple of days ago, see #431 

from rel. 1.14.3 (which we'll release hopefully early next week) you should be able to override the term "VAT" with the one used in your country, at system, organization and event level:
![image](https://user-images.githubusercontent.com/3385346/40292407-7813a1d4-5ccb-11e8-9e74-6a35d15a6ec2.png)

this is only an initial (and pragmatic) effort to allow this kind of modifications. The final goal is to offer a way to override all the messages (see #439 )

I am closing this issue as "duplicate" for now

Celestino

**Comment by aidanmountford** [comment]
Perfect, 

Thank you. 


Aidan Mountford 
FIML, GAICD, GIA(Cert) 

+61-417-849-852 
aidan@mountford.org
