### ISSUE TITLE
Support for a bar code reader that presents as a standard HMI (eg keyboard)

### ISSUE THREAD

**Issue by aidanmountford** [alfio-event/alf.io#445]
Ability to have a "Bar Code" that is read by a handheld barcode wand that "types" the id directly into a field on the screen.

in an environment where we were admitting large numbers of people into a venue the use of the mobile phone caused a number of challenges - a more traditional bar code reader would have been a fantastic option.

**Comment by cbellone** [comment]
this will be addressed in the next rewrite of [Alf.io-PI](https://github.com/alfio-event/alf.io-PI), as the goal is to run it on a regular PC
