### ISSUE TITLE
Reservations should not be deleted automatically when expired

### ISSUE THREAD

**Issue by stephanj** [alfio-event/alf.io#447]
**Is your feature request related to a problem? Please describe.**
Reservations should not get deleted automatically when expired.
This should be a manual task.

**Comment by syjer** [comment]
note: the manual deletion must be applied only for the reservation in the state: payment_pending.

**Comment by syjer** [comment]
method that need some modifications:

 - TicketReservationManager.cleanupExpiredOfflineReservations

**Comment by syjer** [comment]
should be implemented, will do a PR

**Comment by syjer** [comment]
done.
