### ISSUE TITLE
Docker for me not working

### ISSUE THREAD

**Issue by Xohoo** [alfio-event/alf.io#460]
Hi, 
I tried to use the command `docker pull alfio/alf.io` and get this error message

>  Error response from daemon: manifest for alfio/alf.io:latest not found

I tryed it on a debian 9 and a windows 10 machine ---> same error message.
Is there a problem with docker or is the latest tag not defined ?
normaly docker works fine for me.

**Comment by clawfire** [comment]
There's a missing tag "latest" on this repository,

Try `docker pull alfio/alf.io[:version]`. For the latest, it's `docker pull alfio/alf.io:1.14.2`

**Comment by cbellone** [comment]
Hi @Xohoo and @clawfire 
thanks for reporting this. 
Now it should be fixed. 
Thanks!
