### ISSUE TITLE
Check nashorn removal impact http://openjdk.java.net/jeps/335

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#463]
see  http://openjdk.java.net/jeps/335 .

Most likely we will import rhino (?).

To test for sure

**Comment by cbellone** [comment]
as stated in the JEP:

> This deprecation does not affect, in any way, the javax.script API.

since we use javax.script API I think we shouldn't have big issues. In any case, we have to test as soon as a JDK preview is available

**Comment by syjer** [comment]
The use of nashorn specific feature in the script will most likely be the main problem.

See for example: 

https://github.com/alfio-event/alf.io-extensions/blob/master/mailchimp/v1/mailchimp.js#L26

the Java.type is clearly engine specific.

I think we will need to include rhino so we have something stable (?)

**Comment by syjer** [comment]
note: in rhino the interop is unfortunately not as good as nashorn: for example, the java array lists cannot be accessed by index [idx] like the javascript one.
