### ISSUE TITLE
Explore integration of payment provider: revolut

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#472]
Could be an interesting integration: https://www.revolut.com/
Documentation: https://revolutdev.github.io/business-api/#api-v1-0-introduction

**Comment by cbellone** [comment]
update: the "request funds" functionality is not (yet?) exposed through APIs
https://community.revolut.com/t/api-functionality/48698

**Comment by cbellone** [comment]
we could however enhance the "wire transfer" payment method. If the payment recipient is a revolut bank account, we can match the payment by:

- invoice id, or
- reservation ID (either partial or complete), and
- paid amount

and therefore confirm the corresponding reservation.
https://community.revolut.com/t/track-invoice-payments-through-api/18662

**Comment by syjer** [comment]
can be considered done
