### ISSUE TITLE
Pdf rendering: try to reduce memory consumption: don't load the fonts in memory, use temp files

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#481]
see https://github.com/alfio-event/alf.io/commit/d814a3af32537794dbeb78f6874e3f533925ea5f .

Note, we must wait the next release of openhtmltopdf so that https://github.com/danfickle/openhtmltopdf/pull/215 is included.

**Comment by syjer** [comment]
actually: I've committed a fix to only load on demand: https://github.com/alfio-event/alf.io/commit/df7179d4e36bc2e79c21b5abac25ad0f1ef5f83a . 

But still, we need to measure the effective memory consumption of the font embedding process/pdf generation and find a way to reduce it.

**Comment by cbellone** [comment]
can be considered done
