### ISSUE TITLE
Attendee Whitelist

### ISSUE THREAD

**Issue by cbellone** [alfio-event/alf.io#487]
It should be possible to define a whitelist containing, at least in the initial version, email addresses.
It would be then possible to link such whitelist to an event or to a particular category, in order to limit access to events/categories only to selected people.

**Comment by syjer** [comment]
for merging to the master, take a look at:

- src/main/java/alfio/controller/ReservationController.java
- src/main/java/alfio/controller/api/support/TicketHelper.java
- src/main/java/alfio/util/Validator.java
- src/test/java/alfio/manager/GroupManagerIntegrationTest.java
- src/test/java/alfio/manager/TicketReservationManagerTest.java
- src/test/java/alfio/manager/TicketReservationManagerUnitTest.java

**Comment by cbellone** [comment]
done :)
