### ISSUE TITLE
Error on maps.

### ISSUE THREAD

**Issue by andreas-digitalminds** [alfio-event/alf.io#492]
I m trying to add an event on demo and i m getting this error
Event Geolocation is missing. Please check maps' configuration.

**Comment by dutzhk** [comment]
I know it's late but I just tested alfio today. It's freakin awesome!
As instructed by Cellestino in the mail list, be sure to enable this Google Maps APIs and wait for a couple of minutes after; Else, just use Here Maps.

Directions API
Geocoding API
Geolocation API 
Maps Elevation API 
Maps Embed API
Maps JavaScript API
Maps SDK for Android 
Maps SDK for iOS 
Maps Static API
Places API for Web 
Places SDK for Android
Places SDK for iOS
Roads API
Street View API
Time Zone API
