### ISSUE TITLE
Spanish translation 

### ISSUE THREAD

**Issue by TRIXHosting** [alfio-event/alf.io#493]
I want to contribute with Spanish. I'm from Argentina

**Comment by cbellone** [comment]
Hi @TRIXHosting 
thank you!
You can provide a pull request, or - if you're not comfortable with git - you can start translating the project here: https://poeditor.com/join/project/ttBYTmPYdr

Thanks again!
Celestino

**Comment by cbellone** [comment]
see #523

**Comment by mvarona** [comment]
Hi, @cbellone. I'm very interested into contributing to spanish translations, could you please authorize me? Spanish tag appears to me as "pending" in poeditor.

Thanks!

**Comment by cbellone** [comment]
Hi @mvarona,
I have given your account edit privileges on Spanish, now you should be able to add translations.
Thank you for your contribution!

**Comment by mvarona** [comment]
Hi @cbellone, 
Spanish 100% translated, reviewed and ready to ship.
Thanks a lot for your work and for this amazing project!

**Comment by syjer** [comment]
spanish has been added in the master, closing it (see #523 )
