### ISSUE TITLE
Cannot change a user details, without also changing the username.

### ISSUE THREAD

**Issue by dutzhk** [alfio-event/alf.io#503]
**Describe the bug**
If you try changing an existing user's data it is impossible as you get the "There is already another user with the same username." error. In order to change any data, you also need to change the username. As a workaround you can change the username together with whatever data you need, and then change back the username to the original one.

**To Reproduce**
1. Go to Admin panel -> Users
2. Click on Edit for any user
3. Change whatever you want EXCEPT the username

**Expected behavior**
It should be possible to change only the user's data without also changing the username.

Hope I did stumble upon a bug and I'm not just doing something wrong.

Cheers!

**Comment by syjer** [comment]
Closing the issue as it has been fixed
