### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by dutzhk** [alfio-event/alf.io#506]
Hello, I've made a romanian translation in POEditor. 

I do not know how to compile a version with romanian language in it (or just temporary change another language in to romanian one, replace a public.properties file) in order to live test it and make the finishing touches as typos or formatting errors are way easier to spot this way. Just want to make sure the correct translation is in order for the final version.
Also, are diacritical signs supported?

It it possible to compile it for me or send me in the right direction to do it myself?

Thank you!

**Comment by dutzhk** [comment]
I did not know if to edit my original post or write a new comment. I'd rather write a new comment as I managed to resolve this on my own after a couple of hours.
Google + Alf.io readme are my friends :)

Made a new .war file from source using Gradle, in which I changed public.properties and admin.properties files to the ones translated. Temporarily changed EN language to RO, leaving the locale variable to en in order for this to work as there is no romanian language defined yet.

I will test the translation thoroughly for a couple of days and update it in POEditor and hope that in the future it will be added to alfio.

Cheers!

**Comment by cbellone** [comment]
Hi @dutzhk ,
Thank you for your contribution! :-)

How is the test going so far? Are you happy with the translation status?
If yes, we'll add support for Romanian and release it with the next version (no ETA yet). Please let me know

Celestino

**Comment by syjer** [comment]
The translations has been integrated in commit https://github.com/alfio-event/alf.io/commit/0d5b71fa4fd02c0b68cc83ecac7a732b120a70fb .
