### ISSUE TITLE
Can't get admin password, following Docker installation instruction

### ISSUE THREAD

**Issue by raphaeljolivet** [alfio-event/alf.io#509]
I have tried to install Alf.io locally, following the Docker instructions.

The deployement is fine, and I can go to the "admin" login page, but I cannot find the admin password as [explained in the **README** ](https://github.com/alfio-event/alf.io#test-alfio-application)

> Check alfio-web logs: docker logs alfio-web

First `alfio-web` does not refer to any docker image name. I guess this might be `alfio` instead.
But even by changing this, I see no trace of admin password in the logs.

Is it supposed to be generated automatically ? I don't see the "demo" mode being activated in the instructions. Also, which email am I supposed to enter here ?

Thanks for your help.

**Comment by cbellone** [comment]
Hi @raphaeljolivet 
I have fixed the README, thank you for reporting the typo

>First alfio-web does not refer to any docker image name. I guess this might be alfio instead.
But even by changing this, I see no trace of admin password in the logs.

that's weird. The password is auto-generated when alf.io starts up for the first time. 
You should see something like this:

```
20:00:07.316 [main] INFO  alfio.config.DataSourceConfiguration - Quartz scheduler configured to run!
20:00:08.418 [main] INFO  alfio.config.ConfigurationStatusChecker - *******************************************************
20:00:08.419 [main] INFO  alfio.config.ConfigurationStatusChecker -    This is the first time you're running alf.io
20:00:08.419 [main] INFO  alfio.config.ConfigurationStatusChecker -    here the generated admin credentials:
20:00:08.419 [main] INFO  alfio.config.ConfigurationStatusChecker -    abcd 
20:00:08.419 [main] INFO  alfio.config.ConfigurationStatusChecker - *******************************************************
```
can you please destroy/recreate the database container and post the log of a clean startup?
Thanks.

> I don't see the "demo" mode being activated in the instructions. Also, which email am I supposed to enter here ?

The demo profile is for running instances like https://demo.alf.io, and activates some privacy-related enhancements (the events can't be published on the list, and the users expire after a few days)

**Comment by raphaeljolivet** [comment]
Thanks for your help.
Indeed, I had started the alfio container twice : hence it had already created the admin user.
Destroying postgres container did the trick
