### ISSUE TITLE
Additional options are not shown anywere

### ISSUE THREAD

**Issue by raphaeljolivet** [alfio-event/alf.io#516]
I have configured additional options for my tickets, but even when selected by a customer, those do not appear anywere : 
* Ticket sent by email and printed by customer
* Details of reservation in the back office
* Excel export of all ticket sold

How I am supposed to know whether or not someone has purchased a given option ?

**Comment by cbellone** [comment]
Hi @raphaeljolivet ,

you're right: at the moment you can't see additional options unless you've linked an additional attendee info to them. Would be OK to display them in the reservation detail? 

In any case, as a workaround, if you add a new Field under "Attendees data to collect", you can link it to the selection of a specific additional option:
![image](https://user-images.githubusercontent.com/3385346/46318018-6354ae00-c5d5-11e8-9b24-ba7668441124.png)

this way the field value will show up on the Excel export.

Starting from 1.16, additional options will be displayed on the check-in stations, if you use https://github.com/alfio-event/alf.io-PI . We'll update the mobile scan app to display this information soon.

**Comment by syjer** [comment]
As a first step, I've added the order summary in the reservation page in the admin. 

![screenshot from 2018-12-31 16-16-36](https://user-images.githubusercontent.com/498146/50771485-10049280-128b-11e9-93dd-75a2ccf1abb4.png)

**Comment by syjer** [comment]
can be considered done. Further improvements will be done.
