### ISSUE TITLE
Missing documentation how to set up Stripe (willing to help write it)

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#520]
I'm not clear how exactly to set up Stripe in Alf.io?

I do have a Stripe account (and am somewhat familiar with it from already having used it elsewhere).

On Alf.io's `/admin#/configuration/system` the _Stripe's secret key_ and _Stripe's public key_ are obvious - got that. But I don't know what the following are, where to find them on my https://dashboard.stripe.com/account/apikeys :

* _Stripe Connect Client ID_
* _Stripe Connect Callback URL_
* _Stripe Connect WebHook signature key_

The https://stripe.com/docs/dashboard#api-keys which is linked doesn't really mention these either.

On https://dashboard.stripe.com/account/webhooks I can see one can create Web Hooks on Stripe, and on _Add endpoint_ you need to specify an _URL to be called_ (with _Send all event types_ or _Select types to send_ ?) but I don't get if that is a URL on my Alf.io instance, and which?

Perhaps we could clarify this here, and then work it into a doc update... I'm willing to raise a PR e.g. with a section on the README to clarify this - once I actually get it working for myself! :smile_cat: 

Thanks for your help!

**Comment by cbellone** [comment]
Hi @vorburger,

please don't fill in Stripe connect / webhooks options. 
They should be hidden unless "platform mode" has been activated, and the instance owner wants to collect fees from the organizers.

We'll add this to the "v2 todo list", it's time to redesign the settings page...

**Comment by vorburger** [comment]
close via https://github.com/alfio-event/alf.io-website/pull/5 ?
