### ISSUE TITLE
Internal Server Error: expiration must be before the end of the event

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#521]
**Describe the bug**
Hit a funny time rounding error problem somewhere in the code...

**To Reproduce**
1. create an Event that is 2018-11-24 8:30 / 2018-11-24 17:00
2. create three (x3) Categories, with Validity range 1. 8:30 - 10:30, 2. 11:00 - 13:00, 3. 14:00 - 17:00

**Expected behavior**
The categories' date time ranges are valid and this should be accepted.

But instead there is an error saying that: _Internal Server Error: expiration must be before the end of the event_

I was able to work around it by cheating and setting the end time of the category to 16:59 ... :smiling_imp:

**Comment by cbellone** [comment]
see #522, this is the expected behavior, as you can't sell tickets when the event is over

**Comment by vorburger** [comment]
k!
