### ISSUE TITLE
Spanish Translation missing

### ISSUE THREAD

**Issue by joyi6388** [alfio-event/alf.io#523]
Hi! I'm sorry I'm not so good in english writing, but I do understand it very well to be able to translate it. I will love contribute to translate the system to spanish language. I started translate on POEditor and get to 29% complete, but when I went to new page, it threw me back to languages list and Spanish is missing now. I click in Suggest A Language but there is so many spanish variants to pick, and I'm afraid that all my work have lost. Can you please check and let me know so I can continue?. Thank you!

**Comment by cbellone** [comment]
Hi @joyi6388,
thank you very much for your contribution!

I think your translations are still there: https://poeditor.com/projects/po_edit?order=&filter=t&id=199549&id_language=152&search= maybe that was a temporary error?

**Comment by joyi6388** [comment]
Yes there is it! Thank you @cbellone
