### ISSUE TITLE
Customizable Footer

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#529]
In an ideal world, it could be cool if the standard footer proposed in #528 would not be completely hard-coded, but could be customized (perhaps stored in and read from the DB).

For example, I would put "Powered by Alf.io running on OpenShift" into my customization... :smile:

**Comment by syjer** [comment]
Hi @vorburger , yes, we had planned to be able to override any text. I think there is already somewhere an issue :)

**Comment by cbellone** [comment]
See #439

**Comment by syjer** [comment]
done in #439 .
