### ISSUE TITLE
RFE: Keep Expired Reservations details so that they can be approved after all

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#531]
**Is your feature request related to a problem? Please describe.**

I just had a participant pay after their reservation expired (or I was too slow to approve; doesn't matter).

As far as I could see, the only trace one can find in the system in such a case is the E-mail Log? Expired entries do not seem to appear under Reservations anymore - they probably got deleted by the code on expiration.

**Describe the solution you'd like**
In an ideal world, I guess expired reservation could be kept in the system, shown in an "Expired" tab after Competed / Payment Pending / In Process / Cancelled section in the admin UI, and have a sort of "Resurrect" button.

This would not otherwise change the existing functionality. User would still get the email on expiration exactly like now (that is a great feature). 

**Describe alternatives you've considered**

To work around, one can (and I have) simply Create a new Reservation, manually, copy/paste - not the end of the world either, if it happens just once.

**Comment by cbellone** [comment]
Hi @vorburger,

this is something we can do after 2.0M4 (see https://github.com/alfio-event/alf.io/issues/435)

Anyway, right now you can keep reservations whose payment is expired by setting the "Cancel Reservation automatically when payment is overdue" to false (red)

![image](https://user-images.githubusercontent.com/3385346/46766693-05b21700-cce3-11e8-82ea-55547d3bdf1b.png)

**Comment by vorburger** [comment]
> right now you can keep reservations whose payment is expired by setting

oh! That's a great tip - thank you.
