### ISSUE TITLE
STARTTLS for SMTP

### ISSUE THREAD

**Issue by asymmetric** [alfio-event/alf.io#536]
I'm unable to connect to my SMTP server using STARTTLS. If I choose the `smtp` protocol, I get:

    org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first

If I choose `smtps`, I get

    javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: host, port: 587;

In both cases, the port is 587.

**Comment by syjer** [comment]
hi @asymmetric , could you try to add

mail.smtp.starttls.enable=true

in the "SMTP Properties" section of the smtp configuration?

**Comment by asymmetric** [comment]
It worked! Might be worth adding to the documentation.
