### ISSUE TITLE
Login for ticket buyer

### ISSUE THREAD

**Issue by christhonie** [alfio-event/alf.io#537]
I am excited to have discovered this project, which is so close to my requirements and would like to rather contribute here towards a common goal.

In #301 there was a specific mention of:

> Please note that currently alf.io doesn't manage (by design) the identity of the ticket buyer. For v2 I agree that it could be a nice addition, but only if we can make it optional. 

I manage and develop software towards sport event participation, where the buyer's details, and the participants (attendees) associated with the buyer, are tracked from one event to another so that we can consolidate results, re-use personal details, etc.

I would like to see the ticket section (i.e. Step 2 of the reservation process in v2) only become available once the user has logged in. (There are more to this for this particular use case, which I can elaborate on in a separate enhancement discussion, but lets focus on the login for now).

I would like to see an optional, extra step here to require a login, before proceeding to Step 2. I would see this tie in with Spring Security, and possibly with the other discussions around security already touched on elsewhere.

I am able to work on a PR for consideration, but want to see if this is in line with the vision of this product first.

Thanks for a well though out product. It has great potential.

**Comment by syjer** [comment]
hi @christhonie , thank you for considering alf.io :).

Currently, our design/direction is to not _manage_ accounts directly in alf.io but instead, we want to add the integration to a third party identity provider (like keycloak) through oauth. 

As you have noticed the issue #301 is about the admin accounts, but we are open to supporting it for ticket buyer too.

If you are ok with the proposed design, we are more than happy to receive contributions :)

**Comment by christhonie** [comment]
> our design/direction is to not manage accounts directly in alf.io
That will work if you want to offload user management completely to an external application. You can also implement org.keycloak.storage.adapter.AbstractUserAdapterFederatedStorage, which can then leverage your existing user tables in KeyCloak, but to offload the heavy lifting for user management, generating OAuth grants and those UI function to a KeyCloak (or similar alternatives). This way you have an upgrade path for your existing user records, otherwise you have to re-implement your existing user store, possibly resetting the passwords of all existing (admin) users. New installations will however not have this problem.

> we are open to supporting it for ticket buyer too.
Great, that would help me achieve our goals. I will do some planning and revert back to the forum for further input a bit later.

> we really want to focus on the ticketing/event side of the equation
Wise words. Focus on your core value add first and leverage other tools that already do the other stuff well. Many cloud platforms already include their own user management and OAuth implementations, which support your goals for this project.
