### ISSUE TITLE
Waiting queue export (download)

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#549]
**Describe the solution you'd like**
It would be useful to be able to export (download) the Waiting queue, just like you can Download > Attendees Data.

**Describe alternatives you've considered**
I've just manually copy pasted the email addressses of 12 waiters, but that seems sub-optimal :smiley_cat:

**Comment by NassimBounouas** [comment]
Hi,

I've taken a moment to read the attendees data download implementation (frontend and backend) and I think that I can work on this issue.

@syjer  I saw that you worked on the current implementation of the backend  for attendees data download (EventApiController.java). Do you prefer me to follow the same skeleton (same way of implementation)  or can I handle it the way I want ?

**Comment by syjer** [comment]
hi @NassimBounouas, thank you for taking the interest in this issue 👍 

Feel free to implement it in the way you want (I'm quite sure that my code can be improved, maybe we can refactor it with your version) :). When you will do the PR we can do a review together.

**Comment by syjer** [comment]
merged in master with PR #635
