### ISSUE TITLE
Refactor spring security role check

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#556]
Currently all the role check is done inside the spring security configuration. 

It would be simpler to separate it and have a more simpler configuration:

 - in WebSecurityConfig leave only the matcher for requiring authentication
 - in the various controllers, add the @PreAuthorize("hasRole('ROLE_ADMIN')") & co.

Note, for supporting @PreAuthorize we need to add: @EnableGlobalMethodSecurity(prePostEnabled = true)

**Comment by cbellone** [comment]
closing it, according to https://github.com/alfio-event/alf.io/pull/910#issuecomment-635870222
