### ISSUE TITLE
Rewrite admin GUI

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#59]
We should rewrite the admin gui, with a simpler and more robust flow.

To be used: angular 1.5 + angular material ? :D

(Will wait with the next release of angular material: we need date and time picker)

**Comment by syjer** [comment]
TODO:

 - [ ] show all the existing informations
 - [ ] import a material style table
 - [ ] style for all the pages
 - [ ] implement the write/update operations

**Comment by rtack** [comment]
![image](https://cloud.githubusercontent.com/assets/5379/20254379/4c5da120-aa34-11e6-8eb1-b4652f0c5164.png)
commenting here. the color choices are very confusing. why some lines in red, some in black. Makes me think that the lines in red need me to do something but seems not to be the case

**Comment by syjer** [comment]
will be handled in another task
