### ISSUE TITLE
Stripe - Strong Customer Authentication (SCA)

### ISSUE THREAD

**Issue by alessandro-giardina** [alfio-event/alf.io#593]
Here is the text of a Stripe email we received as Italian Agile Movement (original email file attached below):

"_Hi there,In September, the European Union will be introducing rules requiring Strong Customer Authentication (SCA) for many online transactions as part of PSD2 regulation.Our information shows that your business will be impacted by SCA and that you’ll need to make changes to your Stripe integration to become compliant. Transactions that don’t meet the new SCA requirements may be declined by your customers’ banks.Stripe has built a new Payments API—PaymentIntents—to get European customers ready for these rule changes. PaymentIntents is designed to recognize when the new SCA rules apply and to trigger any required authentication.You can learn more in our guide on SCA and read the docs to get started integrating this new SCA-ready payments API._" 

[Stripe message.pdf](https://github.com/alfio-event/alf.io/files/2806936/Stripe.message.pdf)

**Comment by cbellone** [comment]
implemented :-)
