### ISSUE TITLE
RFE: New Event based on an old one (just new date)

### ISSUE THREAD

**Issue by vorburger** [alfio-event/alf.io#598]
**Is your feature request related to a problem?**
I'm [creating my 2nd (real) event with Alf.io](https://tickets.learn.study/) and, unless I'm missing something, it seems that one has to provide the information again and copy/paste retype it, even if a new event is just another "edition" of a previous event?

**Describe the solution you'd like**
One could imagine that Create New Event offers an option to pick from prior events?
Or a Past Event could have an Action to Create New Event?

**Describe alternatives you've considered**
Perhaps one could just add more categories to a past event, but that just seemed wrong.

**Comment by archenroot** [comment]
I think you should be able to do this by writing simple REST API client by taking existing event, change it and send new event request, but from UI its not supported.

**Comment by vorburger** [comment]
I just remembered this issue, as I'm manually copy/pasting a few fields to create a new event... not a big deal, of course - just thought I'd let you know that this could still be a cool feature. Keep rocking! :seedling:

**Comment by syjer** [comment]
@vorburger , I'm working on it :). Expect to be included in the M2 release :D
