### ISSUE TITLE
RFE: Supporting % prepaid ticket with postpaid event onsite

### ISSUE THREAD

**Issue by archenroot** [alfio-event/alf.io#599]
First of all thx for Alf 2.0, amazing rebuild. I like that a lot!

I have scenario as follow:
Ticket payment is required to be done before event in certain % from total price, once user does prepaid in % of total, he/she will pay the rest when attending the event physically. 

I have one workaround, although not maybe good as final solution:
I create 2 categories:
1 - public where I create put a fixed prices and in description I will point out that the price is only related to pre-reservation the seat 
2 - restricted category which will be managed by the operator onsite where he/she will manually checkin clients via restriction codes

What do you think about it?

**Comment by cbellone** [comment]
This is something we are going to address after the model refactoring, which will hopefully happen in M2. 
I am targeting it for M3, just to be on the safe side.
Thanks for this interesting use case! :+1: 

Your proposed workaround should cover the use case for now.
FYI new Tickets can be created directly from the "check-in" functionality (Actions -> check-in) on the backoffice, by clicking on the "Add more attendees" button

![image](https://user-images.githubusercontent.com/3385346/52487199-5f591e00-2bbd-11e9-84da-924e906ad592.png)

then he/she can enter the attendees' data under the hidden category and then perform the check-in
