### ISSUE TITLE
Please accept me as contributor for translating into Japanese language in POEditor project. (POEditor account: martin.henery@protea.co.jp)

### ISSUE THREAD

**Issue by conjoiner** [alfio-event/alf.io#610]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbellone** [comment]
thanks for the translation Martin. 
At the moment we're not ready to generate PDFs with a japanese font. We will solve this issue and add support to japanese in the next releases
