### ISSUE TITLE
 Deleting Additional options not working

### ISSUE THREAD

**Issue by vgowds** [alfio-event/alf.io#611]
While deleting the Additional options, gives internal server error

![image](https://user-images.githubusercontent.com/9523412/52753241-db8ba100-2fc3-11e9-954e-e45a65c29329.png)

**Comment by vgowds** [comment]
![image](https://user-images.githubusercontent.com/9523412/52753879-77b6a780-2fc6-11e9-8387-1e80e385ef71.png)
Problem is only for the first record. If i create second, i can delete

**Comment by syjer** [comment]
hi @vgowds , sorry for the late answer, could you provide a log ?

I'm currently not able to reproduce it .

**Comment by syjer** [comment]
@vgowds I think it's possible that a reservation has used an additional option, so it cannot be removed, the delete button should not be visible in this case.

**Comment by syjer** [comment]
fixed with #613 #634
