### ISSUE TITLE
Stripe - Nothing happen on pay button (ticket sub form)

### ISSUE THREAD

**Issue by Mefl** [alfio-event/alf.io#617]
**Describe the bug**
On subscription form, nothing happen when you select CB by stripe and push the pay button. 

**Expected behavior**
On subscription form, select a non free ticket and select CB by stripe paiement, you can pay.

**Additional context**
The Stripe integration is done by config only secret and public key, therefore Strong Customer Authentication and Stripe connect are disabled. 

Seem a regression of SCA feature.

**Comment by Mefl** [comment]
The required script is not included and therefore there's no payment provider registered on the frontend.

**Comment by cbellone** [comment]
This should be fixed now. Can you please test it and confirm that is now working?
Thanks!
Celestino

**Comment by Mefl** [comment]
It is now working as intented ;)

Thank you !
