### ISSUE TITLE
Support for setting up Facebook pixel (Facebook analytics)

### ISSUE THREAD

**Issue by icougil** [alfio-event/alf.io#621]
Is your feature request related to a problem? Please describe.
Yes, it is, if you want to track your visitors across different sites via Facebook.
In order to set up properly the Facebook Pixel, it is mandatory to introduce some code in alf.io :-/

Describe the solution you'd like
It would be awesome to add your Facebook account in order to have Facebook Pixel setting up in your alf.io management site

Describe alternatives you've considered
Probably the best solution is to add a list of textboxes + checkboxes in the backend in order to see the code that Facebook suggest to include it in alf.io and if the user need/wants to customize it, just be able to change it for every single event (arriving to the checkout, confirmation of a ticket bought, etc)

Additional context
[The official documentation by Facebook](https://developers.facebook.com/docs/facebook-pixel) for setting up the pixel

**Comment by cougil** [comment]
Wops,
Don't you think this feature could make sense? I think it could make a lot of sense for understanding how good (or bad) a campaing is...
Best,

**Comment by doug86i** [comment]
I'd also be interested in this.

Perhaps there is a way to do it with the custom css box?

I'll have a play.

**Comment by doug86i** [comment]
I tried using the pixel image as a background in the custom css and it seems to work.

Here is the code I used:

div.application-container{
 background-image: url("https://www.facebook.com/tr?id=YOUR_ID_HERE&ev=PageView");
}
