### ISSUE TITLE
Rearrange Ticket Categories

### ISSUE THREAD

**Issue by adelia-mobilityone** [alfio-event/alf.io#642]
Hi! When creating a new event(and editing as well), under Categories, I noticed that there's no option to arrange ticket categories. Say later on a new ticket category would be added, it would be nice to be able to rearrange ticket categories as creating a new event (because there's no option to delete events/tickets either) and adding them again would be tedious. Thank you and keep up the good work!

**Comment by cbellone** [comment]
This is now implemented. Thanks @adelia-mobilityone  for pointing it out! :+1:
