### ISSUE TITLE
Replace OkHttp with java 11 HttpClient

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#672]
With java 11, the provided httpclient is good enough. We can drop the okhttp dependency.

Check the possible impact.

**Comment by syjer** [comment]
note, the change it's not an easy one.

**Comment by RushikeshSawant** [comment]
Hi, I would like to work on this for Hacktoberfest. Can you please assign this to me?

**Comment by cbellone** [comment]
Hi @RushikeshSawant, 
that's great, thanks!
I have assigned the issue to you. Looking forward to your Pull Request!

Celestino

**Comment by viveksb007** [comment]
Hi @RushikeshSawant,
Are you working on it? If not can I take this up?

**Comment by RushikeshSawant** [comment]
@viveksb007  yes, I am working on this one, thanks.

**Comment by syjer** [comment]
Closing this issue, thanks to @RushikeshSawant  for the PR https://github.com/alfio-event/alf.io/pull/789 👍
