### ISSUE TITLE
List box multi choice into the Attendees' data to collect

### ISSUE THREAD

**Issue by gBaylaender** [alfio-event/alf.io#675]
Should interesting to have the possibility to create a multi-choice option in the "Attendees' data to collect" in order to collect the most part of data from the audience, in my case I think about language (which language you speak? English, french, Spanish, Italian, German,...)
See example bellow:

![multi-choice](https://user-images.githubusercontent.com/1658712/60499614-1ebb8780-9cb9-11e9-9f93-013fc9fad38f.gif)

**Comment by syjer** [comment]
I've added radio buttons and checkboxes. The disabled options as in the screenshot has not been implemented due to the additional complexity :)
