### ISSUE TITLE
Gross income split by method payments and more accurate?

### ISSUE THREAD

**Issue by gBaylaender** [alfio-event/alf.io#686]
It will be great if is possible to split the gross income value in different method payments in order to be as much possible accurate, add VAT etc.

**Comment by kkrkuldeep** [comment]
@gBaylaender Can you be more specific about the issue.
Where is the issue present, A screenshot will be more helpful.

**Comment by gBaylaender** [comment]
hello @kkrkuldeep 

For example on 
![Screenshot 2020-05-25 at 12 42 20](https://user-images.githubusercontent.com/1658712/82805984-34afd900-9e85-11ea-9667-9f535bf20b91.png)

Will be great to improve the data, by inserting for example, the NET by add the % of Credit Card fees, and other kinds of fees :)
