### ISSUE TITLE
Admin - UX improvements for Languages available

### ISSUE THREAD

**Issue by raffaellar** [alfio-event/alf.io#692]
In place of this
<img width="421" alt="Screenshot 2019-07-20 at 17 31 19" src="https://user-images.githubusercontent.com/44751791/61580611-80cb1800-ab14-11e9-9da6-064c3900c2be.png">
provide the user with:

- a text field, where he can write his content
- a dropdown, where he can select the language of the message
- a button to add another translation

**Comment by cbellone** [comment]
implemented as part of #694
