### ISSUE TITLE
Admin - Active events with 0 events active

### ISSUE THREAD

**Issue by raffaellar** [alfio-event/alf.io#693]
In place of the "no events" message
<img width="387" alt="Screenshot 2019-07-20 at 17 30 57" src="https://user-images.githubusercontent.com/44751791/61580620-99d3c900-ab14-11e9-87b4-ff4c3624a288.png">

add a green button "Create new event"

**Comment by cbellone** [comment]
closed via e754911959af755095d9e801091c870ccf22d27c
