### ISSUE TITLE
Admin - Improvements to Logistic info and description 

### ISSUE THREAD

**Issue by raffaellar** [alfio-event/alf.io#694]
- [x] Name > Event Name
- [x] URL: make the entire url before /event/ visible, still not modifiable
- [x] Move URL down, close to Website URL
- [x] Move Event description up, after Event name
- [x] Owner Organization > Event Organiser
- [x] Location > Event Location. Add a suggestion in the text field to explain that the address should be specified, so that you can show a map
- [x] Image Remove and Reset: keep just one

**Comment by cbellone** [comment]
implemented
