### ISSUE TITLE
Cannot connect the iOS check-in app

### ISSUE THREAD

**Issue by digitall-it** [alfio-event/alf.io#701]
**Describe the bug**
I could not connect the iOS check-in app. It shows an error message upon scanning the login QR provided by the system.

**To Reproduce**
1. Go to alf.io self-hosted instance into Users area
2. Add a new user as a "**Check-in supervisor**" (the problem may be here)
3. Check that your mobile iOS device has network connectivity
4. Scan the QR in the mobile iOS app
5. The error in the screenshot attached appears, a red bar on the top that says "Cannot register a new Account. Please check your internet connection and retry."

**Expected behavior**
The event selection interface appears, the user logs in.

**Screenshots**
![IMG_3265](https://user-images.githubusercontent.com/3578378/61952732-ef94ef00-afb4-11e9-807e-8e18ef923592.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS12.3.1
 - Browser: stock browser, Safari
 - Version n/a

**Additional context**
Self hosted installation version package is "alfio-2.0-M1-1907-boot"

**Comment by cbellone** [comment]
Hi @digitall-it 

I think that the tutorial is outdated, sorry for that. 
Can you please try again creating an API Key instead of a regular user? 

FYI we'll simplify the UI for Users and API Keys soon (see https://github.com/alfio-event/alf.io/issues/697 )

Thanks

**Comment by digitall-it** [comment]
Oh wow, that is a lot better! Thank you!

**Comment by syjer** [comment]
We have finally updated the documentation at https://alf.io/tutorials/check-in/ . I'll close the issue.

Expect a better and unified documentation soon (tm) :)
