### ISSUE TITLE
Improve the Open Graph on page

### ISSUE THREAD

**Issue by gBaylaender** [alfio-event/alf.io#708]
Improve the Open Graph in order, when you share the link on social, the preview it's looking ugly. Is it possible to improve it?

https://ogp.me/

![Image from iOS](https://user-images.githubusercontent.com/1658712/62473013-35656a80-b7a0-11e9-842c-4f1a4b261ba6.jpg)

**Comment by syjer** [comment]
good point. Additionally with the M2 release, we need to check how fb handle single page app.

Tools for preview:  https://developers.facebook.com/tools/debug/sharing/

**Comment by syjer** [comment]
note:

As described in https://speakerdeck.com/sienatime/facebook-sharing-for-single-page-apps

FB does not execute js, so we can generate a server side rendered page if the user agent match.

Will need to test with linkedin and twitter too

**Comment by syjer** [comment]
tool for preview in linkedin: https://www.linkedin.com/post-inspector/inspect/
tool for preview in twitter: https://cards-dev.twitter.com/validator 
doc for twitter: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by syjer** [comment]
note, for fb use localtunnel

**Comment by syjer** [comment]
considered done for M2.
