### ISSUE TITLE
Domain in Email is wrong

### ISSUE THREAD

**Issue by noppelmax** [alfio-event/alf.io#723]
Hey together,

we are having a running system and selling tickets.  But now we have discovered, that the links in the mails are wrong. 

Our website is https://equi-nox.de. But the site alf.io is running on is https://eventlore.de..  So the links should be "https://eventlore.de/event/...." but is "https://equi-nox.de/event/....". I tried to fix is by changing the Event-Url in the Eventsetting. This changed the link in the order-formular but not the links in the email. How could we fix this in a live system?

Kind regards,
Max

**Comment by cbellone** [comment]
Hi @noppelmax ,
the relevant option is:
![image](https://user-images.githubusercontent.com/3385346/63448572-7b782a80-c43e-11e9-8ed7-1f5235b80a00.png)

please log in as **admin** and:
1. make sure that the value in the System configuration is the right one
2. delete the configuration value from the organization and event level

**Comment by noppelmax** [comment]
Ok we found it! Thanks! :)
