### ISSUE TITLE
App login is not working? Ports?

### ISSUE THREAD

**Issue by noppelmax** [alfio-event/alf.io#727]
Hey,

we tried to login with the alf.io App for checkin. I created a "check-in-supervisor" like explained [here](https://alf.io/tutorials/check-in/). 

The app said:
"Cannot register a new account. Please check you internetconnection an retry."

I check the content of the QR-Code by my normal QR App. Password, Username and Baseurl are correct. Do we have to open any additional port? 

Thanks!

Kind regards,
Max

**Comment by cbellone** [comment]
see https://github.com/alfio-event/alf.io/issues/701
unfortunately, the guide is not up-to-date. 
You have to create a Check-In operator API-Key and then scan it.

**Comment by cbellone** [comment]
closing as duplicate

**Comment by ghkobbs** [comment]
Hello, So I am getting the same error as @noppelmax even though I have created a check-in operator API-key. I used a normal qrcode reader to check the contents of the qr-code and it contains the apikey and baseUrl.

Regards

**Comment by cbellone** [comment]
Hi @ghkobbs, can you please give us more details to help us reproduce the issue? 

For example:

- is the alf.io server address public or private?
- are you able to access the admin from the phone's browser? 
- what versions are you using (alf.io scan, alf.io)?

thanks

**Comment by ghkobbs** [comment]
Hello, thanks for the response. 

1. The server address is private for the time being which we access through a vpn.

2. With the vpn turned on, I can access the admin area of alf.io with the phone's browser. 

3. We downloaded the alf.io Scan app from Google play store. 

Thanks in advance

**Comment by cbellone** [comment]
Hi @ghkobbs,

I am afraid it's too much complicated for us to reproduce your issue.
It could be a number of things, including the VPN itself and/or the SSL certificate you use on the alf.io server.

The good news is that the mobile app is open source as well (see https://github.com/alfio-event/Alf.ioBackoffice) so you can debug it using the [NativeScript tooling](https://docs.nativescript.org/angular/tooling/debugging/debugging) and VSCode on your PC. 

let us know if you find the issue! :)

**Comment by ghkobbs** [comment]
Sure. I'll let you know once I manage to debug it.
