### ISSUE TITLE
better PDF invoice name

### ISSUE THREAD

**Issue by digitall-it** [alfio-event/alf.io#743]
**Is your feature request related to a problem? Please describe.**
When downloading all the invoices for further processing, it is natural to order them by chronological order. Unfortunately, the invoice number is at the end of the file, after ID, which prevents it from sorting the PDFs in the file manager.

**Describe the solution you'd like**
I suggest to move the invoice internal ID after the invoice number.

**Describe alternatives you've considered**
No alternatives considered, apart from further renaming.

**Additional context**
Attached a screenshot of the downloaded files. I suggest moving the ID after the invoice number in the generated filename.

![Schermata 2019-09-05 alle 22 51 17](https://user-images.githubusercontent.com/3578378/64379925-35bb8480-d030-11e9-9379-8cdc562b89eb.png)

**Comment by syjer** [comment]
hi @digitall-it , you are right, we will improve the naming so the resulting natural order is better.

**Comment by syjer** [comment]
we have decided that  the last part will be:

YYYY-MM-DD-InvoiceNumber where invoice number is a padded number (up to X characters). Thus the files will be ordered by invoice number.

Additionally, we will remove the uuid, which does not help

**Comment by digitall-it** [comment]
thank you, so if the name of the invoice is "proforma-fattura", the event is called "charity-dinner" and the number is 37, what file name will I get? Because I think the "invoice-" part at the start should be also be dropped in favour of the invoice name. The suggested invoice would be called
proforma-fattura-charity-dinner-2019-09-16-00037.

**Comment by syjer** [comment]
@digitall-it , yep, removing the "invoice-" is a good idea. As you can only download invoices in the archive.

**Comment by syjer** [comment]
@digitall-it the "invoice number/name" (in you case "proforma-fattura-%d") is actually the part of the invoice number. It's not something that we can change.

The resulting name will be:

`charity-dinner-2019-09-16-proforma-fattura-42`
