### ISSUE TITLE
Not possible to login to demo site - Recaptcha check failed

### ISSUE THREAD

**Issue by papadi** [alfio-event/alf.io#815]
Demo site (https://demo.alf.io/authentication) says that Recaptcha check failed but there is no captcha anywhere.

![image](https://user-images.githubusercontent.com/3359377/67304313-ece26100-f4f3-11e9-8ccf-e38a1a65ead2.png)

**Comment by cbellone** [comment]
hi @papadi ,
thanks for reporting it. The issue has been solved (see #783 ) and deployed automatically on the demo site. You can now log in.

Thank you!
