### ISSUE TITLE
Support bancontact payments via Stripe

### ISSUE THREAD

**Issue by jornjambers** [alfio-event/alf.io#821]
**Is your feature request related to a problem? Please describe.**
A lot of people in Belgium only use bancontact

**Describe the solution you'd like**
Option to activate bancontact, as stripe is already supported.

**Describe alternatives you've considered**
n/a

**Additional context**
https://stripe.com/docs/sources/bancontact

**Comment by cbellone** [comment]
bancontact is now supported through Mollie.
