### ISSUE TITLE
Top navbar overlapping display in firefox

### ISSUE THREAD

**Issue by ktm5j** [alfio-event/alf.io#825]
**Describe the bug**
Firefox does not render the top navbar correctly when the browser window is smaller than a certain width.  Causes the left hand elements to render below the right hand elements, causing the bar to obscure page content.  At least it does in the demo

**To Reproduce**
1. Log into demo using firefox
2. Reduce width of browser window until effect occurs

**Expected behavior**
Page elements should be shifted below the navbar when the navbar resizes

**Screenshots**

Correct when window is large enough:
![image](https://user-images.githubusercontent.com/3729107/68037083-5c4b1400-fc9d-11e9-9b25-55abfa5b43e9.png)

What happens when window shrinks:
![image](https://user-images.githubusercontent.com/3729107/68037157-7c7ad300-fc9d-11e9-8c83-d876230eddd7.png)

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Browser: Firefox
 - Version: 69.0

**Comment by kkrkuldeep** [comment]
Can you tell me the HTML file name So, I can fix this issue
