### ISSUE TITLE
Label for PayPal REST API connection description

### ISSUE THREAD

**Issue by patbaumgartner** [alfio-event/alf.io#833]
**Describe the bug**
Label needs to change. In PayPal, the text to connect via REST API does not match the current PayPal UI 

**To Reproduce**
IMPORTANT: if you are going to accept payments in a currency you don't hold, please make sure to enable automatic currency conversion.
To do that, go to PayPal dashboard and select Profile -> Profile and Settings -> My Selling Tools -> Block Payments

**Expected behavior**
Settings -> Account Settings -> Payment preferences -> Block Payments

**Comment by zishxn** [comment]
Hi,
I am interested in solving this issue. Can you please describe how this issue can be reproduced?
Thanks
