### ISSUE TITLE
PayPal redirection issue

### ISSUE THREAD

**Issue by levictorsmith** [alfio-event/alf.io#835]
**Description**
Whether configured to be sandbox/live, the redirect URLs for confirmation and cancel don't successfully redirect back to the event/registration. This may be an error with my configuration, but there's no documentation to go off of, so I've just been winging it.

**To Reproduce**
1. Go to https://events.vocalaffinity.org/event/a-mothers-love
2. Select ticket amount and continue
3. Fill out information
4. Select PayPal option and continue to payment (will redirect you to PayPal's sandbox env)
5. Either: cancel immediately or continue with sandbox account and confirm payment.
6. Observe incorrect redirection (404)

This is the URL that was constructed for cancellation:
https://www.sandbox.paypal.com/cgi-bin/events.vocalaffinity.org/event/a-mothers-love/reservation/b708ed50-84b5-41fc-bf90-fc12d48cc678/payment/paypal/cancel?hmac=716114be7cd6506eabbe070195bd04c23a8176118ef1aa07707f8778b5d9db7e&token=EC-49F9622298734331L

**Expected behavior**
When you cancel or confirm the payment, it should redirect back to the reservation or event page.

Also, the Base URL configuration has been set to events.vocalaffinity.org. No other payment handler has been enabled, other than on-site. If there's something that I configured incorrectly, please let me know.

**Screenshots**
![alfio_1](https://user-images.githubusercontent.com/16521753/69014228-c32f2500-094d-11ea-96a2-7e4d2614d39b.png)
![alfio_2](https://user-images.githubusercontent.com/16521753/69014232-c62a1580-094d-11ea-9756-ac3671e0e53f.png)
![paypalsb_1](https://user-images.githubusercontent.com/16521753/69014236-ce825080-094d-11ea-8fe5-6415a3c00adc.png)
![paypalsb_2](https://user-images.githubusercontent.com/16521753/69014238-d0e4aa80-094d-11ea-8d04-99d4b1fa60db.png)
![paypalsb_3](https://user-images.githubusercontent.com/16521753/69014241-d3470480-094d-11ea-895a-fc9b0f3c4db2.png)

**Comment by cbellone** [comment]
Hi,

thanks for using alf.io!

I think you've found a bug both on alf.io *and* PayPal. Good catch! :-)

Please try to set the base URL setting to https://events.vocalaffinity.org
(including https:// at the beginning)
this should solve the issue.

We'll implement the validation of the URL soon

thanks!






Il dom 17 nov 2019, 22:26 LeVan Smith <notifications@github.com> ha scritto:

**Comment by levictorsmith** [comment]
You are a godsend!! Thank you. This is resolved now.

Thank you so much!

Feel free to reach out if there are any other questions :+1:
