### ISSUE TITLE
URL contains port. Accessing admin page will redirect to wrong auth page.

### ISSUE THREAD

**Issue by j1151300783** [alfio-event/alf.io#841]
URL contains port number. 
EX: https://alf.io:4456/admin#/
Accessing admin page with no-auth will redirect to wrong auth page.
EX: https://alf.io/authentication#/ --> wrong
it should be "https://alf.io:4456/authentication#/".

When auth successful, it also redirect to wrong page.
EX: https://alf.io/admin#/
it should be "https://alf.io:4456/admin#/".

**Comment by cbellone** [comment]
Hi @j1151300783 ,
thanks for using alf.io!

I suspect that you've some issues with your reverse proxy configuration. 
Alf.io doesn't take into account the server port when redirecting to the /authentication URL. 

For example if you run it on your local machine (see [README](https://github.com/alfio-event/alf.io#run-on-your-machine)) the process will listen on port `8080` and redirects on `http://localhost:8080/authentication` as expected

So please double check your configuration. I am closing this since it doesn't look like an issue on our side.

**Comment by j1151300783** [comment]
Thank you for the information~~
I modify my nginx conf and solve the problem.
Thank you very mush.

**Comment by Issamhanzaz** [comment]
Hi @j1151300783 ! Can you maybe share you're Nginx conf? Thanks! #sharingIsCaring

**Comment by j1151300783** [comment]
`
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;
    gzip  on;
    gzip_disable "msie6";

    upstream backend {
        server alfio:8080;
    }

    server {
        listen      80;
        server_name myown.url.com;
        rewrite     ^   https://$server_name$request_uri? permanent;
    }

    server {
            listen 443 ssl;
        server_name myown.url.com;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            ssl_ciphers EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;


        ssl_certificate /etc/nginx/certs/myown.url.com.crt;
        ssl_certificate_key /etc/nginx/certs/myown.url.com.key;

        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            #Must set X-Forwarded-Proto to enable session cookies secure.
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://backend;
        }
    }

    include /etc/nginx/conf.d/*.conf;
}
`
