### ISSUE TITLE
How to print labels using normal printer?

### ISSUE THREAD

**Issue by aadhilpm** [alfio-event/alf.io#867]
How to print labels (badges) using normal printer.

**Comment by cbellone** [comment]
Hi @aadhilpm ,

this is not supported yet. We only support badge printing, for now, using our [Check-in stations](https://alf.io/docs/event-management/check-in/stations/)

In the meantime, you can still download an export from the dashboard, with the fields you need to print and:

- print them using a "merge print" from office suites
- use https://github.com/berteh/ScribusGenerator to fill up badge templates and then print them

I'm closing this issue. It would be great if you could open a proper feature request for the "print badge" functionality. Thanks!
