### ISSUE TITLE
Missing days in the tickets sold chart

### ISSUE THREAD

**Issue by salmar** [alfio-event/alf.io#874]
**Describe the bug**
In the tickets sold / reserved chart from the dashboard, if the hasn't been any tickets sold or reserved on a specific day, that day is skipped. This gives the false impression that there are always reservations just by looking at the chart.

**To Reproduce**
1.- Make reservations on day 1
2.- Make reservations on day 4
3.- Check the chart and you will see no day has 0 reservations, day 2 and 3 are just skipped

**Expected behavior**
All days should appear in the chart. The `/api/events/{eventId}/ticket-sold-statistics` endpoint should include all days (until the event day) both in the `sold` and `reserved` arrays when reservations are 0.

**Screenshots**
<img width="269" alt="Screenshot 2020-02-24 at 17 08 52" src="https://user-images.githubusercontent.com/122109/75170050-d0686680-5729-11ea-9fd3-cb46d344e8fa.png">

**Comment by cbellone** [comment]
implemented and backported to M2. Thanks :+1:
