### ISSUE TITLE
Rest api documentation

### ISSUE THREAD

**Issue by AllanKT** [alfio-event/alf.io#879]
**Is your feature request related to a problem? Please describe.**
I need to build an integration via rest api, and for that I need to understand how requests for alf.io work, but I can't find any sources that can help me understand how to make requests

**Describe the solution you'd like**
for understanding how the application works, documentation for the system would be ideal, from how to perform authentication to how to make calls to http verbs

**Comment by cbellone** [comment]
Hi,
can you please elaborate more on the use case?
i.e. are you building a custom frontend for the reservation process? 

Thanks,
Celestino

P.S.: relevant in case you're trying to integrate Alf.io with your CMS: https://github.com/alfio-event/alf.io/wiki/REST-API-v1

**Comment by samuelstein** [comment]
I'm also interested. Especially in the Check in API because i want to build a Desktop Check in App

**Comment by cbellone** [comment]
@samuelstein interesting. 

FYI we plan to rewrite our [Check-in and badge printing application (Alf.io-PI)](https://alf.io/docs/event-management/check-in/stations/), as a multi-platform application (Raspberry-PI, Linux, Mac, Windows) using JavaFX. 
We need help for this, and if you're interested we would be happy to talk about it.

regarding the Check-in API, it would be great if you could contribute the documentation, of course with our help. WDYT?

**Comment by samuelstein** [comment]
good idea! count me in for the new client.

**Comment by cbellone** [comment]
@samuelstein great, thanks! 
I'll ping you via email so that we can setup a call and discuss how to proceed

**Comment by samuelstein** [comment]
Here is my small cli check-in app: https://github.com/samuelstein/cli-checkin-alf.io. javafx gui will follow soon...

**Comment by cbellone** [comment]
@samuelstein thank you!
