### ISSUE TITLE
Ticket amount is NaN when cancelling a ticket

### ISSUE THREAD

**Issue by salmar** [alfio-event/alf.io#880]
**Describe the bug**
When cancelling an individual ticket from an existing reservation, the amount displayed is NaN.

**To Reproduce**
1. Make a reservation with more than one ticket
2. Go to the reservation
3. Cancel an individual ticket (not the whole reservation)

**Expected behavior**
The right amount to be refunded should be displayed

**Screenshots**
<img width="894" alt="Screenshot 2020-03-19 at 13 04 20" src="https://user-images.githubusercontent.com/122109/77068053-3e7d1200-69e6-11ea-8cfc-c6dd60d60164.png">

**Comment by cbellone** [comment]
fixed and backported to M2-maintenance. Thank you!
