### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by princekwame** [alfio-event/alf.io#905]
Hi @syjer,

After playing around with the software a bit more there are somethings that that I would like to ask some questions around;

**1. Granular User Permissions**
I've noticed that there's no ability to create additional "application" admin accounts and be able to configure granular permissions for it. In the scenario where we have multiple power users but we don't want them to have global admin account, how do we approach this?

Also, I have noticed that there is only 2 roles;

- Organisation Owner
- Check-in Supervisor

![Screen Shot 2020-05-18 at 2 18 02 am](https://user-images.githubusercontent.com/17686117/82153935-e0698f80-98ad-11ea-97f6-84888cace1db.png)

Same scenario as mentioned before, what if we need to have a more granular role that's in-between these default..? A role that doesn't have access to any of the Organisation/Event configuration but is able to see everything in reports/accounting information and process 

![main-portal](https://user-images.githubusercontent.com/17686117/82154090-0a6f8180-98af-11ea-8c04-51d423f486df.png)

Can you please advice me the best way to approach this..? Thank you.

**2. Ability to Sell tickets at gate**
A large part of our event tickets will be sold at the gate when people arrive and badges printed at the gate. How can we manage this kind of workflow?

At the moment the only way I can is use the event link and have an agent go through the same "Purchasing Process" and fill out the details of attendees similar to what the attendees would do themselves, is there a efficient and streamlined process to do this?
 
Apologies re the long post, any assistance will be appreciated.

**Comment by syjer** [comment]
hi @princekwame,

about 

1) Currently, as we never needed a role in between administrator and organization owner, it's not possible. A pull request is  welcome if you think it's a must:)

2) You can create a reservation on the admin side, see our documentation: https://alf.io/docs/event-management/reservations/create-custom/ .

**Comment by princekwame** [comment]
@syjer,

I guess my question was bit layered and I didn't make it clear enough.

What I meant with my 1st question was the ability to have a power user account aside from the Global Admin account. In an environment where you didn't want everyone having Global Admin account access, you would ideally create a less privilege account with a more granular permission set.

The second question that I raised was re the potential of having a 3rd role in-between the "Organisation Owner" and "Check-in User". This third role would be restricted to just Event management, i.e. reservations, reporting, attendee data, and account information.

If we were to implement something within the code;

- How should we approach this?
- What do we need to be aware of when designing this?
- How does alfio approach permissions within the software?

Lots of questions, I appreciate your help with this immensely and thanks for the link, I'll see check it.

**Comment by syjer** [comment]
hi @princekwame , I see what you mean.

For making the discussion more focused, could you please create 2 new issues (as feature request):
one for each new role you are asking with your intended use case, so we can discuss them separately?

In term of implementation, we are using [spring security](https://spring.io/projects/spring-security) to handle the API endpoint, see the current configuration here: https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/config/WebSecurityConfig.java#L336
