### ISSUE TITLE
How to edit event listing & single event layout

### ISSUE THREAD

**Issue by ghkobbs** [alfio-event/alf.io#918]
Hello, thanks to the team and everyone contributing every way they can.

Please I need help changing how events are listed on the homepage (https://test.alf.io/) and the also improve the layout of the detail page for single event(https://test.alf.io/event/free-demo). I went through the files and code but I can seem to find how the layouts/pages are being generated.

Thanks in advance.

**Comment by syjer** [comment]
hi @ghkobbs , the front end is built in this angular project: https://github.com/alfio-event/alf.io-public-frontend .

- event lists: https://github.com/alfio-event/alf.io-public-frontend/tree/master/src/app/event-list
- single event: https://github.com/alfio-event/alf.io-public-frontend/tree/master/src/app/event-display

**Comment by ghkobbs** [comment]
Hi @syjer,

Thanks for the feedback. Just a quick one.

Does it mean that the main project repo does not contain the frontend codes? If yes is it making API calls to the back to retrieve events?

**Comment by syjer** [comment]
@ghkobbs you are right, the main project repository does not contain the public part (it contains the admin, but it's something that we are trying to move out).

The public front end is referenced in the build file (https://github.com/alfio-event/alf.io/blob/master/build.gradle) as a depedency: `com.github.alfio-event:alf.io-public-frontend` .

**Comment by ghkobbs** [comment]
Thank you for pointing me to the right direction. I appreciate the help.

**Comment by ghkobbs** [comment]
Thanks @syjer for the helpful info. I'll leave this open for now and close it in a few days while I work through the files.
