### ISSUE TITLE
Variables in templates

### ISSUE THREAD

**Issue by Issamhanzaz** [alfio-event/alf.io#921]
Hi! 

Where can I find the variables which I can use in the templates?
For example in the "TICKET_PDF" the "{{ticketCategory.name}}" variable is used. But the "{{ticketCategory.description}}" variable isn't working.. 

Thanks!

**Comment by syjer** [comment]
hi @Issamhanzaz , currently the code: https://github.com/alfio-event/alf.io/blob/master/src/main/java/alfio/util/TemplateResource.java#L507 .

You can check the various data types saved in the map.

We will be glad to receive a PR for documenting this part :)

**Comment by Issamhanzaz** [comment]
Hi @syjer , thanks!

Yeah I see them now, but the category description is not available.. Is it maybe possible to do some checks in the template?

for example: 
{{#ticketCategory.name == requestedname}}
     Show this
{{#ticketCategory.name}}

**Comment by syjer** [comment]
hi @Issamhanzaz , we are using https://github.com/samskivert/jmustache which as far as I know does not support out of the box what you are asking.

If you want to provide a PR that add this capability, we will gladly accept.
