### ISSUE TITLE
Error while using mollie

### ISSUE THREAD

**Issue by Issamhanzaz** [alfio-event/alf.io#923]
Hi!

I inserted all the keys from my mollie account in the admin side but when a user use mollie as payment proxy he gets the error: "Payment processing error: An unexpected error has occurred. Please try again."

In the build console there is: "WARN  alfio.manager.payment.MollieWebhookPaymentManager - was not able to create a payment for reservation id fc4bd42b-0edb-4de9-9969-2a013544352c"

Did I do something wrong? In the organization setting there is also a api-key field for mollie, is this one important? 

Is there any documentation of the mollie setup?

Thanks!

**Comment by cbellone** [comment]
Hi @Issamhanzaz ,

At the moment there is no documentation yet for Mollie. It would be great if you could contribute by creating it!

> Did I do something wrong? In the organization setting there is also a api-key field for mollie, is this one important?

yes it is. And probably you need to fill that information. 

We have two usage scenarios for Mollie (the same apply to Stripe):

### 1. single tenant (i.e. you're configuring and using your own Alf.io instance)

in this case you need to create a new webapp  profile and then set the generated API Key in the corresponding Alf.io setting
  
![image](https://user-images.githubusercontent.com/3385346/83777677-fcc94280-a689-11ea-8d84-829c3489ca22.png)

please double check the configuration: Test API Keys cannot be used for Live transfers

### 2. multi tenant (what happens on platforms offering alf.io as a service, like [Swicket](https://swicket.io)) a.k.a. Platform Mode

here you have to create a new application on Mollie, activate it, and then set Client ID, Client Secret and Profile ID to enable the "Connect with Mollie" button
If you have a central redirection point for connected profiles, you must also set the Mollie Connect Callback URL

### Supported Payment Methods

Please note that we support the following payment methods:

- iDEAL
- Credit Cards
- Apple Pay
- Bancontact
- ING Home Pay
- Belfius
- Przelewy24
- KBC
