### ISSUE TITLE
Display event details on label

### ISSUE THREAD

**Issue by ghkobbs** [alfio-event/alf.io#924]
Hello everyone,

According to the docs and label design under an event configuration, It shows that only user's firstname and surname along with his/her title and company name. So far everything works great except my use case requires I display a bit of information about the event (event name & venue) in addition to the existing info on the label.

Kindly help on how to go about it.

Thanks in advance.

**Comment by salmar** [comment]
You can check the following doc for the label configuration: https://github.com/alfio-event/alf.io/blob/master/website/content/en/docs/Event%20Management/Check-in/stations/configure-label.md

The event name and venue can't be used as placeholders but you could use static text to print them ("static-text:Your Event Name")

**Comment by ghkobbs** [comment]
Thanks for your response @salmar.

If it is possible to implement, I am willing to do that myself but I am new to java and can't seem to identify the files to edit. Can you help point me to the files to look at or edit? I want to try my best to see if I can make it work.

**Comment by salmar** [comment]
This doesn't require any coding. 

Go to the event page and select "edit configuration" under the "Actions" menu (upper left corner). Scroll down until you find "Check-in settings" and change the label layout.
