### ISSUE TITLE
Translation of dynamic fields does not work

### ISSUE THREAD

**Issue by ebartz** [alfio-event/alf.io#934]
**Describe the bug**
Whenever I change a translation for somthing that contains dynamic values, after changing the translation the dynamic value is not shown anymore. Instead it just prints out: `foo {1} bar`

**To Reproduce**
1. Create a new Event

2. Change a translation that contains a dynamic value. In my case its the ticket left translation:

![image](https://user-images.githubusercontent.com/6342767/87874275-cf7ded00-c9c8-11ea-9ec9-619748f22fe8.png)

3. Review the event page:

![image](https://user-images.githubusercontent.com/6342767/87874296-02c07c00-c9c9-11ea-846f-721308b7faa6.png)

**Expected behavior**
I do expect, that on the event page it will show `noch 12 übrig`. 

**Additional context**
I also checked the database to see if there is something that gets escaped. The TRANSLATION_OVERRIDE field contains this:

``` json
{
    "de": {
        "common.free": "Kostenlos",
        "reservation-page-complete.your-tickets": "Ihre Tickets",
        "show-event.tickets": "Registrierung",
        "show-event.tickets.left": "noch {0} übrig"
    }
}
```

I also checked this on the global configration level. It also does not work if you change the global translation settings.

**Comment by syjer** [comment]
should be fixed now :)
