### ISSUE TITLE
New Event Type: Hybrid Events

### ISSUE THREAD

**Issue by onedeskoffice** [alfio-event/alf.io#949]
**Is your feature request related to a problem? Please describe.**
Hi guys, we are experiencing a high demand for hybrid events (events that take place simultaneously online and locally). At the moment you can only choose between local or digital events. 

**Describe the solution you'd like**
It would be great if a third option could be selected in the drop down box and the address could be displayed on the event page as well as online dial-in data.
You see, "simply" a hybrid of both options :)

**Describe alternatives you've considered**
I honestly do not know what an "easier" alternative could look like. Maybe another text field under the option "Online Event" where you simply enter the address of the local event. In the frontend this address is then listed under the event type?

Thank you :)

**Comment by cbellone** [comment]
Hi @onedeskoffice ,

agreed! This is becoming more and more important. We must definitely support hybrid events.

Thanks!
