### ISSUE TITLE
I would like organisation to be able to set minimum tickets purchasable per reservation 

### ISSUE THREAD

**Issue by erroldennis** [alfio-event/alf.io#961]
**Is your feature request related to a problem? Please describe.**
Not able to offer group discount applicable to a _minimum purchase_ per reservation.

**Describe the solution you'd like**
Could Alf.io allow for  _minimum_ tickets that may be purchased per reservation.
Currently, the app allows for the _maxim_ tickets purchaseable per reservation.   Adding  _maxim_ tickets would facilitate added flexibility that promo coded lack.

This would facilitate the creation of ticket category where the special group price would apply, only if, say 

- a _minimum amount of tickets_ are purchased, or
- tickets quantities within the  _MIN amd MAX_ range for the category. 

**Describe alternatives you've considered**
Promo code was considered but there is still no minimum purchase setting.

**Additional context**
This will facilitates, for example:  

- _Bye One, Get One Free_  feature  by creating a category with _MIN & MAX of 2 tickets_  purchasable per reservation, but  each priced at 50% of normal price (the 2 tickets priced as 1); or say
- _Bye Five Tickets for the Price of Three_  feature by creating a category with _MIN & MAX of 5 tickets_  purchasable per reservation, but each priced at 3/5 of normal price.

**Comment by cbellone** [comment]
Hi @erroldennis , thanks for your request.

There is an undocumented (yet) feature for creating dynamic discounts. 
You can see the WIP of the documentation here: https://deploy-preview-957--alfio.netlify.app/docs/reference/extensions/

You have to create an extension for the following event: `DYNAMIC_DISCOUNT_APPLICATION`. 
The extension will contain your specific logic to decide whether or not to apply a discount, and will be triggered each time a user updates the ticket selection on the first step of the booking.

a very basic code example for the extension would be:

```javascript
function getScriptMetadata() {
    return {
        id: 'myExtensionIdentifier', // optional: id and version will be used later as a mechanism for checking if the script has a newer version
        displayName: 'My Extension', //mandatory: the name displayed in the configuration page
        version: 0, // optional
        async: false,
        events: [
            'DYNAMIC_DISCOUNT_APPLICATION'
        ]
        //,
        //parameters: {fields: [{name:'name',description:'description',type:'TEXT',required:true}], configurationLevels: ['SYSTEM', 'ORGANIZATION', 'EVENT']} //parameters
    };
}

/**
 * Executes the extension.
 * @param scriptEvent
 * @returns Object
 */
function executeScript(scriptEvent) {
    log.warn('hello from script with event: ' + scriptEvent);
    // your logic here.
    // see documentation for expected parameters and contextual data
    var shouldApplyDiscount = false; //FIXME: replace with your actual logic
    if(shouldApplyDiscount) {
        return {
            amount: 10,
            type: 'PERCENTAGE', // can be FIXED_AMOUNT (per ticket), PERCENTAGE (whole reservation), FIXED_AMOUNT_RESERVATION (whole reservation)
            code: 'YOUR_DYNAMIC_CODE' // if this code does not exist, it will be generated
        }
    }
    return null;
}
```
