### ISSUE TITLE
generate inline css for languages

### ISSUE THREAD

**Issue by cbellone** [alfio-event/alf.io#990]
currently, we have some css code generated for supporting different languages, see:

https://github.com/alfio-event/alf.io-public-frontend/blob/master/src/styles.scss#L39:L49

right now we support more languages thatn the ones listed in the code above.

we should inline this code in the index.html, ideally at build time, so that we can make sure we don't forget to add new languages

**Comment by syjer** [comment]
looks like we don't need to do that :), see PR https://github.com/alfio-event/alf.io-public-frontend/pull/60
